fix(ffe-buttons): Set fixed width for expanded modifier
SpareBank1/designsystem pull request #113
Opened 2018-03-22 11:48 UTC by torbein

Fixes issue #107

2018-03-22 12:41 UTC, selbekk requested changes
Thanks for the contribution! 

Inline the variable instead, this unit isn't a particular candidate for re-use, so I suggest that we don't keep it in its own variable.

2018-03-23 12:11 UTC, torbein commented
Updated and set the variable inline instead.

2018-03-23 12:22 UTC, wkillerud approved these changes

2018-03-23 12:23 UTC, selbekk approved these changes

2018-03-23 12:23 UTC, merged

2018-03-23 12:23 UTC, selbekk commented
Great job - thanks a ton @torbein 👍