fix(ffe-searchable-dropdown-react): Have separate list for highCapaci…
SpareBank1/designsystem pull request #1143
Opened 2021-06-30 14:18 UTC by MariaOverlierBerg

…ty and lowCapacity

... HighCapacityList.js is not working for screen readers.
BREAKING CHANGES: You have to pass prop `highCapacity` in order to have lists with hundreds of items

## Beskrivelse

Viser HighCapacityList dersom det er definert.
Viser LowCapacityList dersom highCapacity ikke er definert. Denne lista er sånn lista var før i la opp til at det var mulig med highCapacity (https://github.com/SpareBank1/designsystem/commit/d5dc190bbb34986da928b6925a6396d6a78d62c6#diff-213c799381ade1e9ed80e204dd0ecc109f061b1c1abc4790fe4cfe0a5ee88a75)

Fjerna også ubrukt logikk i reduceren.

## Motivasjon og kontekst

Lista for `highCapacity` gjør at skjermleser på iPhone ikke lenger funker. Så frem til vi finner en fiks på det (som er litt vanskelig), viser vi kun lista for `highCapacity` når det er definert. Det var sånn det fungerte før etter vi skrev om kontovelgeren og searchable-dropdown. I tillegg til at skjermleser ikke funker på highCapacity-lista, så skjer det noen stylingbugs mtp. høyde og lignende som vi har slitt litt med med `VirtualizedList`. Så jeg tenker at hvert fall foreløpig er det best å kun bruke highCapacity-lista når det er nødvendig. 

## Testing

Har et eksempel for highCapacity og flere for lowCapacity og har testet på disse, men har ikke testa med skjermleser. Får ikke testa på mobil, men du Peter hadde en måte å lage et testmiljø så vi kan teste på mobil? Hadde du hatt mulighet til å vise meg hvordan vi gjør det? :) 

Er det forresten sånn at det blir en ny major version nå som det er en breaking change? Det vil si at versjonen vi bruker i account-selector, ikke vil automatisk oppdatere seg til denne nye versjonen?

2021-06-30 18:22 UTC, pethel commented
@MariaOverlierBerg 

Jag lagde en bruker her 
https://www.netlify.com/

sedan er det bare att bygga hela greja med `npm run build`

resultatet av bygget er ju en dist mappe 

![image](https://user-images.githubusercontent.com/2248579/124011891-cbcc5600-d9e0-11eb-84ae-d4d9eb032047.png)

drag and drop på den distmappen under new site

![image](https://user-images.githubusercontent.com/2248579/124011639-86a82400-d9e0-11eb-906e-f6347706da0f.png)

Du vill da få en url du kan bruke

2021-06-30 18:30 UTC, pethel requested changes
Hade noen kommentarer men det allra viktigaste med denne PR er ju att det virker på iPhone

2021-06-30 18:30 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/LowCapacityList.js
> +const LowCapacityList = ({
Kanske kallet den noe som ikke LowCapacity i seg? Det er ju ikke så lav kapicitet. Kanske `Result`?

2021-06-30 18:30 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                    {state.isExpanded &&
Så lenge det er samme props kan man gjøre slik
```
const ResultElement = highCapacity ? HighCapacityList : LowCapacityListEllerVadViKallerDen

 <ResultElement
        listBoxRef={listBoxRef}
                                listToRender={state.listToRender}
                                ListItemBodyElement={ListItemBodyElement}
                                highlightedIndex={state.highlightedIndex}
                                dispatch={dispatch}
                                dropdownAttributes={dropdownAttributes}
                                locale={locale}
                                refs={refs}
                                onChange={onChange}
                                isNoMatch={state.noMatch}
                                noMatch={noMatch}
                                noMatchMessageId={noMatchMessageId.current}
                                focusInput={focusInput}
                            />

```

2021-07-01 08:07 UTC, MariaOverlierBerg commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                    {state.isExpanded &&
Åh nice!!! Det var en lur greie.

2021-07-01 08:45 UTC, pethel approved these changes

2021-07-01 08:49 UTC, merged