Hardkode farger
SpareBank1/designsystem pull request #1173
Opened 2021-08-31 12:53 UTC by NghiNg

Farger med tint() blir ikke eksportert riktig

## Beskrivelse

## Motivasjon og kontekst
For å kunne importere fargene herfra 

import { black, fargeLyng, fargeSyrin } from '@sb1/ffe-core';

slik som 

import { black, fargeLyng30, fargeSyrin70 } from '@sb1/ffe-core';

## Testing
har ikke testet

2021-08-31 13:15 UTC, antidecaf commented on packages/ffe-core/less/colors.less
> +@ffe-farge-fjell-70: #4d689f);
Her er det et parentes i hex-koden som må fjernes.

2021-08-31 13:26 UTC, antidecaf commented
Takk for PR!

Endringene ser greie ut, men commit-meldingen må endres litt på før denne kan merges. Meldingen må skrives i henhold til [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Dette er fordi publisering og generering av versjonsnummer og changelog gjøres automatisk basert på commit-meldingen. [Mer info om format og bakgrunn her](https://github.com/SpareBank1/designsystem/wiki/Bidra:-Fra-issue-til-pull-request#commit-meldinger).

I dette tilfellet bør meldingen være noe a la:

`fix(ffe-core): hardkoder fargevariabler for å tilgjengeliggjøre de i js`

2021-09-01 09:58 UTC, kwltrs requested changes
Jeg er ikke overbevist om at dette er rett sted for å fikse det, men at `packages/ffe-core/bin/build.js` burde endres. `tint` er en gyldig less-funksjon og vi burde ikke begrense oss på et subset av less fordi ett script snubler.

2021-09-17 12:20 UTC, kwltrs commented
Ble fikset i #1204

2021-09-17 12:20 UTC, closed without merging