Toggle switch-komponent
SpareBank1/designsystem pull request #1299
Opened 2022-01-06 10:09 UTC by antidecaf

## Beskrivelse

Ny komponent som passer for valg som kan skrus av eller på, med umiddelbar respons. Under panseret er dette en checkbox.

**Skjermskudd:**

![image](https://user-images.githubusercontent.com/463847/148364083-ae5fa0e4-4a5a-434d-8e20-9bf49dbc35b1.png)

Dette viser lys og mørk variant i følgende states:

* default
* default + hover
* valgt
* valgt + hover
* fokus (tastatur)

**Eksempler som viser transitions mellom forskjellige states:**

Hover, valgt
![image](https://i.imgur.com/r4qjT7X.gif)

Fokus
![image](https://i.imgur.com/auwGz4f.gif)

Dark mode - hover, valgt
![image](https://i.imgur.com/O1V9wii.gif)

Dark mode - fokus
![image](https://i.imgur.com/oetwuYx.gif)

## Motivasjon og kontekst

Dette er en gjenoppliving av en gammel PR (#527) for ny ToggleSwitch-komponent. I etterkant av at den forrige ble lagt på is har behovet blitt revurdert og vi har kommet frem til at vi likevel ønsker en slik komponent.

2022-01-06 11:07 UTC, HeleneKassandra commented
Jeg får bare en vanlig checkbox og ikke noe styling på denne når jeg prøver å kjøre opp branchen og se på den i component-overview? Jeg prøvde å bygge ffe-form-react på nytt, og kjøre opp, men forsatt samme feil

2022-01-06 11:18 UTC, antidecaf commented
> Jeg får bare en vanlig checkbox og ikke noe styling på denne når jeg prøver å kjøre opp branchen og se på den i component-overview? Jeg prøvde å bygge ffe-form-react på nytt, og kjøre opp, men forsatt samme feil

Vanskelig å si noe om hva det kan skyldes, men antar du må kjøre et clean build før du starter opp serveren igjen. Alle screenshots er fra component-overview lokalt hos meg.

2022-01-06 11:58 UTC, HeleneKassandra approved these changes
Fikk det til å funke :+1: 

Da er det bare å huske å oppdatere dokumentasjonen også!

2022-01-06 12:44 UTC, MariaOverlierBerg approved these changes
:star_struck:

2022-01-12 14:22 UTC, HeleneKassandra requested changes
Andrea har noe design input, som potensielt vil føre til noen endringer, så bare endrer min approved status til "request changes" sånn at vi ikke med ett uhell merger denne.

2022-02-24 15:18 UTC, antidecaf commented
Ny PR med litt flere features og endringer etter tilbakemeldinger kommer snart :)

2022-02-24 15:18 UTC, closed without merging