Legg til hvit farge-variant og andre design tweaks
SpareBank1/designsystem pull request #1300
Opened 2022-01-10 16:37 UTC by HeleneKassandra

## Beskrivelse
Legger til en variant av alle boksene med hvit bakgrunn i lightmode, denne skal brukes der man tar i bruk
boksene på farget bakgrunn, og man ikke oppnår god nok kontrast med standard versjonen. 

I tillegg er det noen design endringer i noen av meldingsboks-typene, samt fargeendringer for å samkjøre alt med det som ligger i Figma.

### ContextMessage
- Fjernet muligheten til å legge til egne ikoner, nå brukes satte ikoner pr type. Info = utropstegn, Success = Hakeikon etc..
- Både compact og vanlig versjon har alltid ikon. Dette er for å oppfylle WCAG krav om at informasjon ikke bare skal gis gjennom farge.
- Lukke ikonet har fått endret fokus styling fra outline to border, dette er for å unngå at fokus-markeringen gjør boksen høyere og/eller at den vises utenfor meldingsboksen. 
- Compact varianten har nå blitt høyere, som konsekvens at vi oppfyller krav til klikkbar flate (lukke-knapp).
- Lagt til hvit variant for bruk på farget bakgrunn i lightmode. 
- Farge-tweaks
-  Header extender nå .ffe-strong-text og ikke h5-stylingen med mindre man sender inn custom klasse/headerElement. 

### MessageBox
- Endring av CSS-hierarki
- Lagt til hvit variant, for bruk på farget bakgrunn i lightmode.
- Farge-tweaks

### SystemMessage
- Farge-tweaks
- Lagt til hvit variant, for bruk på farget bakgrunn i lightmode.

## Motivasjon og kontekst

Det har vært ett ønske om å få en variant som fungerer bedre på bruk på farget bakgrunn. Denne prosessen
førte også med seg noen andre visuelle endringer som ble tatt med i samme slengen. Endringene finnes også som en egen branch i Figma som merges inn samtidig som denne PR'en 

## Testing

Testet med å kjøre opp lokalt og sjekke ting opp mot component-overview.

## Andre ting som må gjøres før denne kan merges
[ ] Merge i Figma
[ ] Oppdatere dokumentasjon

2022-01-12 13:21 UTC, kwltrs requested changes

2022-01-12 13:21 UTC, kwltrs commented on packages/ffe-context-message-react/src/ContextErrorMessage.js
> +import { UtropstegnIkon } from '@sb1/ffe-icons-react';
Denne er litt problematisk hvis man ikke har tree shaking. Bedre med en default import:

```js
import UtropstegnIkon from '@sb1/ffe-icons-react/lib/utropstegn-ikon'
```

2022-01-12 13:21 UTC, kwltrs commented on packages/ffe-context-message-react/src/ContextErrorMessage.js
> +            icon={<UtropstegnIkon />}
Vet dette at vi har dette fra før. Synes dette er stygt. Er det enkelt å få det til at man kan slenge inn klassen og ikke en instans? F.eks
```js
<ContextMessage icon={UtropstegnIkon} ..../>
```

2022-01-12 13:21 UTC, kwltrs commented on packages/ffe-context-message-react/src/ContextMessage.js
> +                { 'ffe-context-message--coloredbg': onColoredBg },
Penere å slå de to objektene sammen til ett:
```js
className={classNames(
    'ffe-context-message',
`    ffe-context-message--${type}`,
    {
        'ffe-context-message--compact': compact, 
        'ffe-context-message-coloredbg': onColoredBg
    },
    className,
)}

2022-01-12 13:21 UTC, kwltrs commented on packages/ffe-context-message-react/src/index.d.ts
> +    onColoredBg: boolean;
`onColoredBg` er ikke required, ikke sant? Burde det da være `onColoredBg?: boolena;`?

2022-01-12 13:21 UTC, kwltrs commented on packages/ffe-context-message/less/ffe-context-message.less
>          &-svg {
Vi har en uskreven regel om å ikke dele opp i navnet på en block eller element i nesting men å dele de mellom block og element (dvs. `&__xxx`) eller før en modifier (`&--xxx`). Har du mulighet å fikse det?

2022-01-12 14:17 UTC, HeleneKassandra commented on packages/ffe-context-message-react/src/ContextErrorMessage.js
> +            icon={<UtropstegnIkon />}
Jeg tenkte det samme, men grunnen til at det er sånn er fordi brukere skal ha muligheten til å sende inn custom klasser til ikonet direkte, uten at det er en egen property.  Vi går jo bort fra custom ikoner nå, men teknisk sett er det forsatt mulig hvis man bruker ContextMessage komponenten istedenfor ContextErrorMessage for eksempel, derfor jeg lot det bare være.

Er det noe vi ønsker å lage issue på?

2022-01-12 14:20 UTC, HeleneKassandra commented on packages/ffe-context-message/less/ffe-context-message.less
>          &-svg {
Litt usikker på hva du mener her? Mener du bare å flytte de 3 reglene over .native-reglene sånn at alt står samlet uten å bli splittet av en annen nesting?

2022-01-17 10:09 UTC, kwltrs commented on packages/ffe-context-message/less/ffe-context-message.less
>          &-svg {
Mener reglene som kommer etter.

Do:
```css
.ffe-context-message-content {
   &__header { ... }
   &__header-svg { ... }
}
```
Don't:
```css
.ffe-context-message-content {
   &__header {
       ...
       &-svg { ... }
   }
}

2022-01-18 09:31 UTC, kwltrs approved these changes

2022-01-24 10:52 UTC, andrea-sb1 approved these changes

2022-01-28 09:18 UTC, merged