searchable-dropdown / account-selector: change labelId to labelledById
SpareBank1/designsystem pull request #1303
Opened 2022-01-12 12:25 UTC by torkjels

Siden man kan gi inn en `id` til input-elementet kan man gi dropdownen et label uten å **måtte** bruke `aria-labelledby`. Så den kan gjøres optional. I tillegg endrer jeg den fra `labelId` til `labelledById`, siden det er mer beskrivende etter min mening.

2022-01-12 13:16 UTC, MariaOverlierBerg submitted a review, later dismissed

2022-01-12 13:46 UTC, HeleneKassandra requested changes
Jeg er litt usikker på om det å ikke gjøre labelledById required er en god ide. Men det har muligens mer med at det burde vært required andre steder.  F.eks InputGroup har verken inputid eller labelId som required, så med endringen din risikerer vi at folk ikke sender med id i det hele tatt.

2022-01-12 13:46 UTC, HeleneKassandra commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js
> +    labelledById: string,
Kan du legge til forklaring på denne propertyen også, sånn som du gjorde i SearchableDropdown?

2022-01-12 14:01 UTC, torkjels commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js
> +    labelledById: string,
Jepp, godt tenkt! Fiksa nå :heavy_check_mark:

2022-01-12 14:23 UTC, torkjels commented
> Jeg er litt usikker på om det å ikke gjøre labelledById required er en god ide. Men det har muligens mer med at det burde vært required andre steder. F.eks InputGroup har verken inputid eller labelId som required, så med endringen din risikerer vi at folk ikke sender med id i det hele tatt.
> 
> Ellers er det gjort riktig med tanke på markering av breaking change +1 :)

@HeleneKassandra i betaling bruker vi label som blir generert i InputGroup, og id'en som sendes ned til AccountSelector/SearchableDropdown blir generert av InputGroup og satt på input-elementet i SearchableDropdown. Og InputGroup sitt label har htmlFor på den id'en. Så vi vil ikke spesifisere aria-labelledby. Vi får ikke tak i id'en på label-elementet til InputGroup sånn uten videre heller, så da måtte vi ha generert vår egen labelId og sendt inn til InputGroup, og det er jo ganske knot det og.

Vi kunne ha lagt på feks `labelId` på InputGroup sin `extraProps` som sendes videre til children, men da mater vi plutselig en prop med navnet `labelId` direkte ut til children, og da kan det jo hende at vi feks får `<input>`-elementer hvor vi prøver å sette attributten `labelId` og det er jo ikke gyldig HTML.

Så jeg kom fram til at dette ble beste løsning uten å ty til større endringer, men tar gjerne imot gode idéer! :smiley:

2022-01-14 11:53 UTC, HeleneKassandra approved these changes
Skjønner! Glemte at InputGroup generered Id hvis ingenting er spesifisert!

2022-01-14 12:17 UTC, merged