chore: oppdater README
SpareBank1/designsystem pull request #1325
Opened 2022-02-17 11:44 UTC by HeleneKassandra

Oppdaterer README da vi blant annet ønsker å ha mer informasjon i dokumentasjonen enn rett i readme.
En del av informasjonen var også litt utdatert eller litt overlapp med det vi nå har i dokumentasjonen.

2022-02-17 11:59 UTC, kwltrs requested changes

2022-02-17 11:59 UTC, kwltrs commented on README.md
> +### :computer: Kjøre opp designsystemet lokalt
```suggestion
## :computer: Kjøre opp designsystemet lokalt
```

2022-02-17 11:59 UTC, kwltrs commented on README.md
> +## :mag: Hvordan se hva som er nytt
Føler denne avsnitt burde fjernes fra README og flyttes til dokumentasjonen som FAQ e.l.
Og dette med `ncu` må vi ikke ha med videre.

2022-02-17 11:59 UTC, kwltrs commented on README.md
> +Designsystemet består av innholdet i dette repoet (ofte refert til som FFE), verktøykassen i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://www.design.sparebank1.no). Alle diss
Kanskje verd å nevne at det er vår intern sb1u-slack og ikke tilgjengelig til eksterne?

2022-02-17 12:19 UTC, andrea-sb1 commented on README.md
> +Verktøykassa i Figma blir oppdatert av designsystem-teamet ved endringer, eller når nye ting legges til. Endringene annonseres enn så lenge via interne kanaler - spør fagleder, så blir du pekt i rikt
```suggestion
Designsystem-bibliotekene i Figma blir oppdatert av designsystem-teamet ved endringer. Du får melding i Figma om at det finnes en ny oppdatering og kan velge om du vil at skissene dine skal oppdateres med de nyeste endringene med en gang eller vente til senere. :+1:
```

2022-02-17 12:29 UTC, andrea-sb1 commented on README.md
```suggestion
Designsystem-teamet deler jevnlig rundt hva som skjer i designsystemet – blant annet i designforum, nyhetsbrev og på Slack.
```

2022-02-17 12:35 UTC, andrea-sb1 commented on README.md
> +## :mag: Hvordan se hva som er nytt
Synes også det er godt forslag å flytte «Hvordan se hva som er nytt» til FAQ 👍

2022-02-17 14:43 UTC, HeleneKassandra commented on README.md
> +## :mag: Hvordan se hva som er nytt
Enig med å flytte  den Hvordan se hva som er nytt til FAQ.   Men den npm check for update delen, tenker du at vi skal fjerne den helt? Eller flytte den under "guide til github" ?

2022-02-17 15:01 UTC, kwltrs commented on README.md
> +## :mag: Hvordan se hva som er nytt
Vekk med ncu. Det kommer ut nye tools hver måned, så gidder ikke å vedlikeholde sånn småtteri i en README.

2022-02-17 15:05 UTC, kwltrs commented
Skal vi kanskje endre på H1en "Felles Front End i SpareBank 1?

2022-02-17 15:06 UTC, kwltrs commented on README.md
>  [![Coverage Status](https://coveralls.io/repos/github/SpareBank1/designsystem/badge.svg?branch=master)](https://coveralls.io/github/SpareBank1/designsystem?branch=master)
Kan du ta vekk disse buttons? Vi bruker ikke de tjenestene.

2022-02-18 08:51 UTC, HeleneKassandra commented
> Skal vi kanskje endre på H1en "Felles Front End i SpareBank 1?

Finnes bedre overskrifter ja, men det som er bra med den er at den forklarer litt hvorfor vi referer til designsystem koden som FFE

2022-02-18 09:10 UTC, antidecaf commented on README.md
> +bidrag. Ta en titt på [Bidra seksjonen](https://design.sparebank1.no/bidra/alle-kan-bidra/) i dokumentasjonen om hvordan du går frem.
```suggestion
bidrag. Ta en titt på [Bidra-seksjonen](https://design.sparebank1.no/bidra/alle-kan-bidra/) i dokumentasjonen om hvordan du går frem.
```

2022-02-18 09:10 UTC, antidecaf commented on README.md
> +Komponentene i FFE er delt opp i to NPM-pakker. Pakkene som har "-react" i navnet inneholder react-komponenten samt tester, og de uten inneholder alle less filene.
```suggestion
Komponentene i FFE er delt opp i to NPM-pakker hver. Pakker med `-react` i navnet inneholder react-implementasjon og tester, mens øvrige pakker inneholder (Less-basert) styling.
```

2022-02-18 09:10 UTC, antidecaf commented on README.md
> +Designsystemet består av innholdet i dette repoet (ofte refert til som FFE), verktøykassen i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://www.design.sparebank1.no). Alle diss
```suggestion
Designsystemet består av innholdet i dette repoet (ofte referert til som FFE), verktøykassen i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://design.sparebank1.no). Alle disse delene håndteres av designsystem-teamet, som kan nås på vår interne Slack i #ext-designsystem, via mail på [designsystem@sparebank1.no](mailto:designsystem@sparebank1.no) eller via GitHub issues.
```

2022-02-18 11:30 UTC, andrea-sb1 commented on README.md
> +Designsystemet består av innholdet i dette repoet (ofte referert til som FFE), verktøykassen i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://design.sparebank1.no). Alle disse
```suggestion
Designsystemet består av innholdet i dette repoet (ofte referert til som FFE), designsystem-bibliotekene i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://design.sparebank1.no). Alle disse delene håndteres av designsystem-teamet, som kan nås på vår interne Slack i #ext-designsystem, via mail på [designsystem@sparebank1.no](mailto:designsystem@sparebank1.no) eller via GitHub issues.
```

2022-02-18 15:26 UTC, kwltrs commented on README.md
> +Designsystemet består av innholdet i dette repoet (ofte referert til som FFE), verktøykassen i Figma og dokumentasjonen som finnes på [design.sparebank1.no](https://design.sparebank1.no). Alle disse
...(ofte referert til som Felles Frontend, forkortet til FFE)

2022-02-21 12:20 UTC, andrea-sb1 submitted a review, later dismissed

2022-02-21 14:09 UTC, merged