feat(ffe-chart-donut-react): Support setting background for the circle
SpareBank1/designsystem pull request #1411
Opened 2022-07-14 09:57 UTC by ivarni

Adds support for providing a `background` prop that will be used to decide
the fill of the inner SVG circles in the donut. This defaults to "none" but
"white" can also be used if the donut is rendered on a coloured background.

## Beskrivelse

Legger til støtte for å sette bakgrunnen til donut'en til hvit

## Motivasjon og kontekst

Har et design der denne brukes i en grid-col med bakgrunnsfarge og ønsker leselig kontrast på innholdet

## Testing

Skrevet unit-tester

2022-07-14 13:43 UTC, kwltrs requested changes
Med darkmode blir det litt feil å ha en hvit bakgrunn, uansett er kontrasten da også for lav.

![image](https://user-images.githubusercontent.com/493924/178996348-0e2b71f0-2d94-4be0-a3cf-02c087d464c1.png)

2022-07-15 03:54 UTC, ivarni commented
Ok... vi har ikke darkmode så det er litt vanskelig for meg å forholde meg til, men hva skal endres da? Defaulten er satt til det samme som i dag så det høres ut som en enkel fiks for de som bruker darkmode er å ikke sette bakgrunnen til hvit?

2022-07-18 10:08 UTC, kwltrs commented
@ivarni Kanskje man legge til en boolean-prop som slår på en css-klasse `ffe-chart-donut--with-background` og som da legger til hvit bakgrunn lightmode eller svart i darkmode?

Jeg har testet chart-donut på forskjellige bakgrunner og for meg virker det som den lysblåe halvsirkel har for lite kontrast når det blir en annen bakgrunnsfarge enn hvit. Teksten har nok kontrast. Er det grunnen til denne endringen? I så fall kan vi kanskje endre bare fargen på den lysblå halvsirkelen.

2022-07-18 10:16 UTC, ivarni commented
@kwltrs Nei, grunnen er at jeg har fått en skisse der figuren er plassert i en lyseblå boks men fortsatt har hvit bakgrunn. Dagens implementasjon har `fill="none"` og er derfor transparent. 

Derfor ender vi opp med 
![image](https://user-images.githubusercontent.com/379849/179491068-67175dab-444c-43f3-98cd-5084862eac42.png)

I stedet for
![image](https://user-images.githubusercontent.com/379849/179491118-67df5623-83d6-4290-b78f-4190988f6d72.png)

I darkmode vil jeg anta at den nåværende transparente bakgrunnen fungerer ekstremt dårlig allerede. I og med at det heller ikke er laget typescript-definisjoner for denne komponenten har jeg egentlig en gnagende mistanke om at det bare er vi som bruker den siden jeg tror hele banken allerede er godt over på TS?

2022-07-18 10:18 UTC, ivarni commented
Det er forøvrig ikke den eneste forskjellen mellom denne komponenten i Figma og denne komponenten i FFE, men det var den mest synlige.

2022-07-18 10:41 UTC, kwltrs commented
Jeg finner ikke chart-donut i vår figma-biblioteket. Derfor anser jeg implementeringen som fasiten. Men kanskje vi kan ta det i vår slack-kanal hva som er i figma?

> I darkmode vil jeg anta at den nåværende transparente bakgrunnen fungerer ekstremt dårlig allerede.

[Det fungerer rett bra](https://sparebank1.github.io/designsystem/chart_donut_ChartDonut). Vi la till darkmode på donuten en god stund siden.

> I og med at det heller ikke er laget typescript-definisjoner for denne komponenten har jeg egentlig en gnagende mistanke om at det bare er vi som bruker den siden jeg tror hele banken allerede er godt over på TS?

Jeg har ikke helt oversikt men jeg tror den blir også brukt i BM.

2022-07-18 10:45 UTC, ivarni commented
Hm. Jeg sitter med en skisse her der den er i bruk:
https://www.figma.com/file/gEz8KCgLtg0XgKqfqXEqf7/R%C3%A5dgivningsl%C3%B8sning-fondsbytte?node-id=781%3A77291

For min del kan vi fint si at dagens implementasjon er fasit og så heller ta det opp dersom noen reagerer på bakgrunnsfargen. Det virker jo som det er en del divergens mellom hvordan de forskjellige systemene tenker at den skal se ut så det hadde kanskje ikke vært så dumt med en full avstemming.

2022-07-18 14:51 UTC, ivarni commented
Da lukker jeg denne og så ser vi hva som kommer ut av slack-tråden. Vi er nede i én designer og hun har ferie de to neste ukene (tror jeg det var)

2022-07-18 14:51 UTC, closed without merging