fix(ffe-form-react): fjerner støtte for aria-invalid på radiobtn
SpareBank1/designsystem pull request #1429
Opened 2022-08-09 11:12 UTC by HeleneKassandra

## Beskrivelse
Fjerner støtte for aria-invalid på BaseRadioButton.

## Motivasjon og kontekst
Det er ikke tillatt med aria-invalid på input type="radio". 

## Testing
Kjørt opp lokalt

2022-08-09 11:24 UTC, HeleneKassandra commented
Litt usikker på om jeg bør fjerne stylingen til invalid også?

2022-08-09 11:31 UTC, kwltrs commented
> Litt usikker på om jeg bør fjerne stylingen til invalid også?

Tenker du på klassen `ffe-radio-button--invalid`?

2022-08-09 11:43 UTC, HeleneKassandra commented
> 
Ja. Litt usikker på om den blir brukt? Fordi da jeg satte aria-invalid før jeg gjorde noen endringer, så så jeg ingen endringer. Men da jeg la klassenavnet inn i className="" så syntes den. Så litt usikker på om noen bruker den ved  å toggle klassen direkte på RadioButton

2022-08-09 11:49 UTC, kwltrs commented
> Så litt usikker på om noen bruker den ved å toggle klassen direkte på RadioButton

Om det ikke er lov å ha aria-invalid på denne ifølge WCAG, ser jeg ingen grunn til å beholde invalid-styling. Det er litt av det samme.

2022-08-10 12:41 UTC, kwltrs requested changes
Jeg føler at b57fec9bb506107cd16f41a520d3ca15f76603c2 burde også være BREAKING CHANGE

2022-08-18 06:40 UTC, kwltrs approved these changes

2022-08-18 09:16 UTC, merged