fix(ffe-context-message): Now supports using Paragraphs in darkmode
SpareBank1/designsystem pull request #1430
Opened 2022-08-10 11:13 UTC by ivarni

Previously the font-color would become light grey iny any `ffe-body-paragraph`
included inside a `ffe-context-message`. Now it becomes black instead.

## Beskrivelse

Gjør at `ffe-body-paragraph`er inni en `ffe-context-message` får svart farge i darkmode, siden den lysgrå som er standarden ikke fungerer på den bruke bakgrunnen til disse meldingene

## Testing

Kjørt opp lokalt og verifisert visuelt for ContextTipsMessage eksemplene i både light og dark mode
(Endret også navn på disse slik at de har samme navn som komponenten de skal vise fram)

2022-08-10 12:24 UTC, HeleneKassandra approved these changes

2022-08-10 12:32 UTC, kwltrs requested changes

2022-08-10 12:32 UTC, kwltrs commented on packages/ffe-context-message/less/ffe-context-message.less
>      .ffe-body-text {
.ffe-body-text trenger ikke være med.

2022-08-10 13:07 UTC, ivarni commented on packages/ffe-context-message/less/ffe-context-message.less
>      .ffe-body-text {
![image](https://user-images.githubusercontent.com/379849/183908814-53f036bd-c7da-4e84-aae0-66c83e208b65.png)

Jo, hvis man fortsatt skal støtte å bruke denne uten en paragraph. Jeg kan godt fjerne det men da må jeg oppdatere de andre eksemplene også + gjøre den til breaking

2022-08-10 13:16 UTC, kwltrs commented on packages/ffe-context-message/less/ffe-context-message.less
>      .ffe-body-text {
Ah, skjønner. Fikk ikke med meg at ContextTipsMessage wrapper children i en ffe-body-text. Det var litt uheldig. Men vi tar det kanskje i en egen PR senere.

2022-08-10 13:17 UTC, kwltrs approved these changes

2022-08-10 13:17 UTC, merged

2022-08-11 07:26 UTC, ivarni commented on packages/ffe-context-message/less/ffe-context-message.less
>      .ffe-body-text {
Lurer på om det hadde vært enklere å holde disse meldingene litt mer konsistent om de bodde i samme npm-pakke og delte samme base-component.

2022-08-11 07:54 UTC, kwltrs commented on packages/ffe-context-message/less/ffe-context-message.less
>      .ffe-body-text {
> Lurer på om det hadde vært enklere å holde disse meldingene litt mer konsistent om de bodde i samme npm-pakke og delte samme base-component.

Den tanke kommer opp jevnlig, f.eks #917 ;-)

2022-08-11 13:37 UTC, ivarni commented
SmallText og MicroText har forøvrig samme issue...