Refaktorering av grid
SpareBank1/designsystem pull request #1450
Opened 2022-09-20 13:51 UTC by antidecaf

## Beskrivelse

* [Flex](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout)-styling er skrevet om til [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout).
* `ffe-grid`/`<Grid>` har ikke lenger noe luft i topp eller bunn by default. Luft over og under kan i stedet legges til på grid-rader ved hjelp av disse modifierne:
    * `.ffe-grid__row--padding` / `<GridRow padding={true}>`
    * `.ffe-grid__row--margin` / `<GridRow margin={true}>`
* `.ffe-grid__row-wrapper` er ikke lenger nødvendig å bruke for å legge bakgrunnsfarge på rader
* En del modifiere er fjernet:
    * Modifere som endrer rekkefølge på kolonner i en rad:
        * `.ffe-grid__row--reverse`
        * `.ffe-grid__row--horizontal`
    * Modifiere som endrer plassering av innhold i hver kolonne:
        * `.ffe-grid__col--reverse`
        * `.ffe-grid__col--horizontal`
        * `.ffe-grid__col--start`
        * `.ffe-grid__col--center`
        * `.ffe-grid__col--end`
        * `.ffe-grid__col--top`
        * `.ffe-grid__col--middle`
        * `.ffe-grid__col--bottom`
        * `.ffe-grid__col--around`
        * `.ffe-grid__col--between`

Foruten modifierne som er fjernet fungerer både api-et i `ffe-grid-react` og styling i `ffe-grid` likt som før.

## Motivasjon og kontekst

Grid-komponenten er kompleks og overveldende å forholde seg til. Den er i utgangspunktet tenkt å være et verktøy for å lage layouter, spesielt på sidenivå, men inneholder i dag en rekke valgmuligheter som tildels går i beina på hvordan grid brukes som verktøy i designprosessen. Stylingen er også skrevet om for å redusere kompleksitet. 

## Testing

Testet lokalt, i Chrome, Firefox og Safari

2022-09-21 12:40 UTC, kwltrs requested changes
Ser bra ut :+1: 

Kan du liste opp de fjernete modifiers i commit meldingen til ffe-grid slik at det blir med i CHANGELOG?

2022-09-22 13:38 UTC, antidecaf commented
> Kan du liste opp de fjernete modifiers i commit meldingen til ffe-grid slik at det blir med i CHANGELOG?

Done.

2022-09-22 16:37 UTC, kwltrs approved these changes, later dismissed

2022-09-27 11:46 UTC, kwltrs approved these changes

2022-10-04 08:51 UTC, merged