AccordionItem - put className prop last
SpareBank1/designsystem pull request #1451
Opened 2022-09-26 13:59 UTC by tutturen

## Beskrivelse

Jeg opplever at det er vanskelig å override default styles på AccordionItem - og jeg tror at det er fordi className man passer inn som prop kan bli overstyrt av `.ffe-accordion-item`.

Så jeg har lagt opp en PR som et forslag - sette className som sendes inn som prop til sist, slik at den det blir lettere å overskrive eksisterende styling.

2022-09-26 14:10 UTC, kwltrs requested changes
Koden er ok, men kan du sjekke at commit-meldingen fungerer med conventional commits?

2022-09-26 14:27 UTC, pethel requested changes
Jag skjønner ikke att dette skall gjøre noen forksjell

https://stackoverflow.com/questions/15670631/does-the-order-of-classes-listed-on-an-item-affect-the-css

Det som har og si er vell css specificity: Ikke rekkefolgen på klasserna som er listade.

2022-09-27 05:22 UTC, tutturen commented
@pethel har rett - dette gjør ingen forskjell. Jeg testet det nå.

2022-09-27 05:22 UTC, closed without merging

2022-09-27 06:09 UTC, pethel commented
> @pethel har rett - dette gjør ingen forskjell. Jeg testet det nå.

Du kan ju eventuellt se på om det er mulig og endra css så att den lettare kan øverskrivas