feat(ffe-header): legg til darkmode styling og fix #1516
SpareBank1/designsystem pull request #1521
Opened 2022-11-21 15:32 UTC by HeleneKassandra

## Beskrivelse
Bytter ut less fargevariabler med css variabler, legger  til darkmode styling og oppdaterer focus styling på linker. 
Fikser også #1516  ved å bytte ut button-condensed med ` padding: 4px 16px ` som er det som er brukt live i dag på den knappen. 

Darkmode styling som er lagt til: 
![Skjermbilde 2022-11-21 kl  16 26 52](https://user-images.githubusercontent.com/39946146/203094200-d216f101-b14a-4856-b609-a78782746690.png)

Oppdatert focus:
![Skjermbilde 2022-11-21 kl  16 27 06](https://user-images.githubusercontent.com/39946146/203094260-efa8de71-99cc-4444-94da-870e133e9cb3.png)

## Motivasjon og kontekst
Sett på i sammenheng med theming, og oppdaget ting underveis som jeg valgte å ta meg tiden til å forbedre. 
Fokus stylingen ble oppdatert for å matche mer det vi har andre steder. 

## Testing
Kjørt opp lokalt

2022-11-22 13:26 UTC, antidecaf commented on packages/ffe-header/less/ffe-header.less
> +        padding: 4px 16px;
Kunne vi brukt spacing-variabler her? Verdiene tilsvarer noen av de vi bruker fra før.

2022-11-22 13:41 UTC, antidecaf requested changes
`:focus`/tastaturnavigering er litt buggy i `.ffe-header__user-nav` etter disse endringene. Staten vises nå kun i dark mode, men endrer utseendet på hover-state i light mode. Ikke overbevist om at outline/box-shadow funker så godt i akkurat denne menyen.

Her har "Postkasse"-linken fokus:
![Screenshot 2022-11-22 at 14 30 49](https://user-images.githubusercontent.com/463847/203327457-83bc57e1-7659-4954-a5f6-fbaffaac5d37.png)

Hover på den fokuserte linken (legg merke til avrunda hjørner):

![Screenshot 2022-11-22 at 14 30 33](https://user-images.githubusercontent.com/463847/203327348-a2b8d4e4-0d44-4987-862c-966d0b19597f.png)

Fokus i dark mode:
![Screenshot 2022-11-22 at 14 31 48](https://user-images.githubusercontent.com/463847/203328063-74a448a2-ab47-4cbb-8c7c-47a20f2c1178.png)

Sånn så fokus ut tidligere (endret bakgrunnsfarge):
![Screenshot 2022-11-22 at 14 31 06](https://user-images.githubusercontent.com/463847/203328312-63efb04c-22fe-4ceb-9158-4f318adf099b.png)

2022-12-05 15:08 UTC, HeleneKassandra commented
Har endret basert på tilbakemeldingene, dette er nå focus i lightmode:
![Uploading Skjermbilde 2022-12-05 kl. 16.05.04.png…]()

Hover:
![Skjermbilde 2022-12-05 kl  16 05 12](https://user-images.githubusercontent.com/39946146/205671093-aa7a9f80-b3dd-4da9-a6ae-9addd9fd55e9.png)

Focus darkmode: (Her er jeg litt usikker på om det er bra nok?) 
![Skjermbilde 2022-12-05 kl  16 05 26](https://user-images.githubusercontent.com/39946146/205671138-dae4bd68-1446-4952-865d-6dcdc822cd93.png)

hover darkmode:
![Uploading Skjermbilde 2022-12-05 kl. 16.05.17.png…]()

2022-12-06 10:42 UTC, antidecaf commented
Ser bedre ut! Eneste jeg kan se sånn umiddelbart nå er at fokus-outlinen på brukernavn og logg ut-knappen kanskje burde være hvit i stedet for blå i dark mode? Så henger de sammen med hvordan fokus ser ut på tilsvarende elementer rundt forbi.


![Screenshot 2022-12-06 at 11 39 29](https://user-images.githubusercontent.com/463847/205889574-bc6e791c-30b8-4f2c-a436-c68659a8af19.png) ![Screenshot 2022-12-06 at 11 38 10](https://user-images.githubusercontent.com/463847/205889577-1021b605-dcf4-4195-b207-6dda7436e482.png)

2022-12-06 12:48 UTC, HeleneKassandra commented
> Ser bedre ut! Eneste jeg kan se sånn umiddelbart nå er at fokus-outlinen på brukernavn og logg ut-knappen kanskje burde være hvit i stedet for blå i dark mode? Så henger de sammen med hvordan fokus ser ut på tilsvarende elementer rundt forbi.
> 
> ![Screenshot 2022-12-06 at 11 39 29](https://user-images.githubusercontent.com/463847/205889574-bc6e791c-30b8-4f2c-a436-c68659a8af19.png) ![Screenshot 2022-12-06 at 11 38 10](https://user-images.githubusercontent.com/463847/205889577-1021b605-dcf4-4195-b207-6dda7436e482.png)

Skjønner ikke helt hvorfor den fikk den fargen på focus, fordi den skal egentlig extende .ffe-button:focus::after stylingen og så vidt jeg vet har ffe-button også hvit border?  Uansett overskrev det i siste commit.

2022-12-22 11:33 UTC, kwltrs approved these changes

2023-01-03 14:59 UTC, merged