feat(ffe-searchable-dropdown-react): remove high capacity prop
SpareBank1/designsystem pull request #1556
Opened 2023-01-03 15:09 UTC by pethel

Visst borde man kunna kunna undgå att react-virtualized blir med i bundle slik?

2023-01-03 15:16 UTC, MariaOverlierBerg submitted a review, later dismissed
Nice!

2023-01-03 15:16 UTC, MariaOverlierBerg commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +    const ResultsElement = results || Results;
Trenger kanskje ikke `Results` lenger her siden `results` har `Results` som default verdi :smile: 
Kan sikkert også bare droppe hele `ResultsElement` og heller bare bruke `results` direkte.

2023-01-03 15:16 UTC, MariaOverlierBerg commented on component-overview/examples/dropdown/SearchableDropdown-isLoading.jsx
> +import {SearchableDropdown} from '@sb1/ffe-searchable-dropdown-react';
Samme de andre stedene :smile: 
```suggestion
import { SearchableDropdown } from '@sb1/ffe-searchable-dropdown-react';
```

2023-01-04 07:36 UTC, pethel commented on component-overview/examples/dropdown/SearchableDropdown-isLoading.jsx
> +import {SearchableDropdown} from '@sb1/ffe-searchable-dropdown-react';
Ordnet

2023-01-04 07:40 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +    const ResultsElement = results || Results;
Sånn

2023-01-04 08:09 UTC, pethel commented
Ser AccountSelectorn er broken. Skall se på det

2023-01-04 10:29 UTC, MariaOverlierBerg approved these changes, later dismissed

2023-01-05 07:12 UTC, torkjels submitted a review, later dismissed
FIn endring, bra jobba! :heavy_check_mark:
(bygget feiler pga en linting-feil)

2023-01-05 09:58 UTC, kwltrs requested changes
Takk, Peter!

En småting: kan du oppdatere README.md til searchable-dropdown slik at import-eksemplet er riktig?

2023-01-05 11:05 UTC, pethel commented
> Takk, Peter!
> 
> En småting: kan du oppdatere README.md til searchable-dropdown slik at import-eksemplet er riktig?

Sure! 
Skall vare i orden nå

2023-01-05 11:18 UTC, kwltrs approved these changes

2023-01-05 11:20 UTC, merged