bug: Längre text gör att UA styling kickar in och centrerar texten i Accordion Heading.
SpareBank1/designsystem pull request #1594
Opened 2023-04-17 08:27 UTC by jberglund

## Beskrivelse
Det är inte ett problem när texten är kortare eftersom att flexbox är vänster justert.

Så här ser det ut med lång text, utan fix:
<img width="740" alt="Screenshot 2023-04-17 at 10 23 32" src="https://user-images.githubusercontent.com/706565/232427782-1a3b023a-863a-4ba6-aa92-f7ee2d04eee9.png">

Med fix:
<img width="698" alt="Screenshot 2023-04-17 at 10 24 07" src="https://user-images.githubusercontent.com/706565/232427927-e497a6ed-13cb-4bec-b8b1-2fa3c31daa3d.png">

2023-04-17 08:31 UTC, HeleneKassandra submitted a review, later dismissed

2023-04-17 08:35 UTC, HeleneKassandra commented
Supert! Takk for at du lagde PR :D

2023-04-17 10:06 UTC, antidecaf approved these changes

2023-04-17 10:12 UTC, antidecaf requested changes
`text-align` er allerede definert i linje 47, og skal i utgangspunktet løse problemet du viser til. Har du evt prøvd å endre verdien fra `start` til `left` der det allerede er satt? Eller kan det være en overstyring fra et annet stylesheet inne i bildet?

2023-04-17 10:40 UTC, jberglund commented
Ja, jag såg det jag också. Intressant. `text-align: start` ska ju vara stöttat och det är ju mer "rätt" mtp RTL, men det ser ut som den blir bortagen när det kompileras.

https://design.sparebank1.no/komponenter/accordion/ även här så är inte `text-align: start` med, så ska vi bara byta ut `start` med `left` och ta bort duplikaten då?

2023-04-18 12:31 UTC, antidecaf commented
> Ja, jag såg det jag också. Intressant. `text-align: start` ska ju vara stöttat och det är ju mer "rätt" mtp RTL, men det ser ut som den blir bortagen när det kompileras.
> 
> https://design.sparebank1.no/komponenter/accordion/ även här så är inte `text-align: start` med, så ska vi bara byta ut `start` med `left` och ta bort duplikaten då?

Tror vi bare må prøve det. 😅 Jeg er litt i stuss på hvorfor text-align ikke kommer med ut på design.sparebank1.no. Den er imidlertid tilstede og funker som forventet i [eksempelet på component-overview](https://sparebank1.github.io/designsystem/accordion_Accordion). Dette er den samme koden som kjører på urlen du viser til.

2023-04-18 12:31 UTC, antidecaf approved these changes

2023-04-21 11:52 UTC, HeleneKassandra commented
Kan du rebase denne pr'en så det blir en commit med en commitmelding som starter med "fix(ffe-accordion):" 

Jeg ville endret det selv og merget for deg, men er redd for å gjøre feil siden det kommer fra en "fork" istedenfor ett klonet versjon av repoet

2023-04-21 13:22 UTC, HeleneKassandra commented
Lagde ny PR som erstatter denne med riktig commitmelding, så slipper du å bruke tid på å rette navnene osv! 
Tusen takk for fiks!

2023-04-21 13:22 UTC, closed without merging