feat(ffe-searchable-dropdown-react): ts prop
SpareBank1/designsystem pull request #1631
Opened 2023-06-23 08:16 UTC by AOD-sparebank1

typer for innerRef

## Motivasjon og kontekst

## Testing

2023-06-23 09:25 UTC, pethel requested changes

2023-06-23 09:25 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/index.d.ts
> +    innerRef?: React.Ref;
Vad med?
 ```
 innerRef?: React.Ref<HTMLInputElement>;
```

Det er ref til ett inputfelt vell. Ser det er brukt andre steder i designsystemet iaf der refen er til en input.

2023-06-26 07:28 UTC, pethel approved these changes

2023-06-26 08:48 UTC, HeleneKassandra approved these changes

2023-06-26 09:14 UTC, merged