Legg til Material Symbols
SpareBank1/designsystem pull request #1644
Opened 2023-07-19 15:37 UTC by HeleneKassandra

## Beskrivelse
Oppretter to pakker for implementering av Material Symbols i FFE.
Pakkene er:
- ffe-symbols som har selve ikon-fonten og styling-klasser.
- ffe-symbols-react som er react komponenten

Pakkene importeres også i component-overview og det er lagt til flere eksempler som viser de ulike propertyene man kan sette på symbol komponenten. 

## Motivasjon og kontekst
Vi skal på sikt gå over til å bruke material symbols istedenfor ikonene som per dags dato finnes i FFE-Icons. Siden det er en helt ny implementering + ett annet ikon utvalgt valgte vi å opprette 2 nye npm-pakker og deprecate ffe-icons over tid, istedenfor å komme med en breaking change i eksisterende pakke. Dette vil forhåpentligvis gjøre overgangen smoothere for alle involvert. 

## Testing
Kjørt opp lokalt og testet i komponent overview + kjørt npm run test for å kjøre de ulike unit testene.

2023-07-19 21:12 UTC, antidecaf commented
Usikker på hvorfor, men fonten lastes ikke i eksemplene på Azure.

<img width="321" alt="image" src="https://github.com/SpareBank1/designsystem/assets/463847/e0f6f7e2-6908-4e6b-8e58-82e775c8a4c7">

2023-07-21 11:20 UTC, HeleneKassandra commented
> Usikker på hvorfor, men fonten lastes ikke i eksemplene på Azure.
> 
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/463847/254712147-e0f6f7e2-6908-4e6b-8e58-82e775c8a4c7.png">
> Regner med det er en bug med en logisk løsning. :) For øvrig ser det veldig solid ut!

Jeg er faktisk ikke sikkert på hvorfor dette skjer?? Fordi når jeg inspecter css fila, så kommer inline fonten med??

2023-07-24 11:37 UTC, antidecaf requested changes

2023-07-24 11:37 UTC, antidecaf commented on packages/ffe-symbols-react/src/Symbol.js
> +    size: oneOf(['small', 'medium', 'large', 'xlarge']),
I `index.d.ts` er det kun `fill` som er frivillig prop, mens her er det kun `children` som er required. De bør helst stemme overens med hverandre :)

2023-07-24 11:40 UTC, HeleneKassandra commented on packages/ffe-symbols-react/src/Symbol.js
> +    size: oneOf(['small', 'medium', 'large', 'xlarge']),
Bra spottet! Fikset nå

2023-07-24 11:43 UTC, antidecaf submitted a review, later dismissed

2023-08-15 08:44 UTC, antidecaf approved these changes

2023-08-15 12:26 UTC, merged