feat(datepicker): add innerRef to Datepicker
SpareBank1/designsystem pull request #1775
Opened 2024-02-06 09:10 UTC by tuva-odegard

## Beskrivelse

Datepicker har fått en innerRef man kan sende inn for å bruke ref på komponenten utenifra. 
innerRef er optional og komponenten skal fungere som før ellers. Det er lagt til eksempel på bruk i Datepicker.jsx.

Om koden: 
Fra før av brukte datepicker this.dateInputRef som ref, og det er litt uklart om denne fortsatt må være der for at denne endringen skal fungere. Alternativt ville jeg skrevet ref = { innerRef } på linje 352 i stedet for funksjonen, men da er det mulig mer må endres. Åpen for tilbakemeldinger med bedre måter å gjøre det på, men gitt at det er en gammel komponent føles det som den tryggeste måten å gjøre det på.

## Motivasjon og kontekst

Team kjøretøy bruker ref.focus() for å kunne lenke til feil i skjemaer, og Datepicker har ikke kunne blitt referert til via ref. Denne endringen er laget for å kunne bruke ref.focus() på inputfeltet til Datepicker utenifra, via useRef(). 

Motivasjonen bak oppgaven har blandt annet vært denne kodesnutten, hvor vi ønsker å fjerne den øverste delen: 
`onClick={() => {
                      if ("deliveryDate" === key) {
                        const deliveryDate = document.getElementById(
                          "datepicker-wrapper-deliveryDate"
                        );
                        deliveryDate.getElementsByTagName("input")[0].focus();
                      } else {
                        const errorRef: Ref = get(errors, key).ref;
                        if (errorRef.focus) {
                          errorRef.focus();
                        }
                      }
                    }}`

## Testing

Testet ved å lage en knapp som brukte innerRef.current.focus() i Datepicker.jsx, som beviste at innerRef referer til input-elementet. Ellers var det vanskelig å teste for de spesifikke tilfellene Team Kjøretøy trenger det til. 

Har ikke skrevet eller oppdatert noen tester. Gjorde et forsøk, men klarte ikke å finne en god test på om input-feltet får en ref fra innerRef.

2024-02-06 09:56 UTC, antidecaf approved these changes

2024-02-06 13:56 UTC, antidecaf requested changes
Takk for bidraget! Jeg var visst litt rask med å approve denne. 😄 

Commit-meldingen må samsvare med pakkenavnet for at Lerna skal kunne publisere endringene til npm på riktig måte. `feat(datepicker):` må med andre ord endres til `feat(ffe-datepicker-react):`.

component-overview er en egen pakke, så endringene i denne mappen må ha en egen commit med melding som prefixes med type og pakkenavn på samme måte, f.eks `docs(component-overview): `

2024-02-06 14:28 UTC, tuva-odegard commented
@antidecaf Ah, takk for at du sa i fra! 😃 Må det også legges til som to forskjellige pull-requests?

2024-02-07 10:19 UTC, antidecaf commented
> @antidecaf Ah, takk for at du sa i fra! 😃 Må det også legges til som to forskjellige pull-requests?

Nei, det holder med to separate commits i samme pull request :relaxed:

2024-02-12 06:58 UTC, tuva-odegard commented
@antidecaf Ble det riktig nå? 😃

2024-02-22 10:00 UTC, antidecaf commented
> @antidecaf Ble det riktig nå? 😃

Ser sånn ut 😄

2024-02-22 10:00 UTC, antidecaf approved these changes

2024-02-22 10:01 UTC, merged