Ny detail list card komponent
SpareBank1/designsystem pull request #1832
Opened 2024-03-11 15:02 UTC by HeleneKassandra

## Beskrivelse
Legger til ny komponent som heter DetailListCard.
![Skjermbilde 2024-03-11 kl  09 15 48](https://github.com/SpareBank1/designsystem/assets/39946146/15c29633-2764-4ffa-a238-84793a5194f9)

## Motivasjon og kontekst
Denne komponenten finnes mange steder i mange ulike applikasjoner, så tok på meg jobben med å endelig få den inn som en komponent i designsystemet. 

Komponenten brukes til å vise informasjon, og det finnes mange ulike varianter der man noen ganger har klikkbare rader og andre ganger ikke. 

## Testing
Kjørt opp lokalt i component overview.

2024-03-11 18:55 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +            &:hover,
Tror vi burde ta en runda med og skjula hover på device men man kan ju begynne her om man ønsker allrede: Provade selv på emualtorn og så ut att funka. 
https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices/64553121#64553121

2024-03-11 19:01 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +            <dd className="ffe-detail-list-card__item-value">
Mulighet att man skille vilja ha flere dd?  På ditt screenshot ser jag før meg att kontoeier feks kan var 2. En som eier men man kanskje ønske rog skrive ut disponent under  tyP

```
Kontoeier                    Ola Nordman
                                      Lisa Nordman(disponent)
```
Eller det kanske er en egen dt?

2024-03-11 19:02 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +            <dd className="ffe-detail-list-card__item-value">
value kunde i sånne fall vart string eller liste av strings?

2024-03-11 19:11 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
en href på en div blir galet.  Att laga en a istellet for div er dessverre ikke heller greit.
![image](https://github.com/SpareBank1/designsystem/assets/2248579/fff2a382-20ad-488b-ac75-690245cb69d0)

Kanske den som bruker komponenten må stoppa lenkarna i dt eller dd selv. onClick kan vell stå men ju den som bruker komponenten sitt ansvar att passa på en god del ting

2024-03-11 19:11 UTC, pethel commented on packages/ffe-cards-react/src/index.d.ts
> +    href?: string;
href er riktigt men tenker nok den ikke burde vare der som jag skriver om i andra kommentarer.

2024-03-11 19:13 UTC, pethel commented on packages/ffe-cards-react/src/index.d.ts
> +    onClick?: func;
onClick?:  React.MouseEventHandler<HtmlVAD_DET_NU_BLIR_TIL_SLUTElement> ;

2024-03-11 19:14 UTC, pethel commented on packages/ffe-cards-react/src/index.d.ts
> +    label?: React.ReactNode | string;
label: React.ReactNode | string;
 
 Denne må vare båkrevd man kommer ingen vei utan den?

2024-03-11 19:17 UTC, pethel commented on packages/ffe-cards-react/src/index.d.ts
> +    value?: React.ReactNode | string;
value: React.ReactNode;
 
 Denne må vare båkrevd man kommer ingen vei utan den? En string er også en React.ReactNode
 https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype 
 
Kunde vurdert denne da null/undefined også er  React.ReactNode

2024-03-11 19:18 UTC, pethel commented on packages/ffe-cards-react/src/index.d.ts
> +    children?:
children:

children er ikke optional?

2024-03-11 19:19 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +        gap: 8px;
var(--ffe-spacing-xs); eller vafd det blir

2024-03-11 19:20 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +        grid-template-columns: 1fr 2fr;
Test fjerne slik test brekker på smala skjermer og høy text zoom. Jag bruker FF når jag tester.

2024-03-11 19:21 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +        grid-template-columns: 1fr 2fr;
Ellers er flex og flex wrap dine beste venner når det kommer til text-zoom :)

2024-03-12 07:58 UTC, HeleneKassandra commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +            <dd className="ffe-detail-list-card__item-value">
Visuelt så ville jeg heller ha vist disponent som en egen <dt>/<dd>,
Tenker vi holder komponenten enklest mulig så lenge det lar seg gjøre, akkurat det caset du nevner så kunne man bare ha slengt det inn i samme dd om man ikke ville hatt det på egen linje

2024-03-12 08:00 UTC, HeleneKassandra commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Koden du tester her er ikke helt den som blir generert, fordi jeg legger på "role" avhengig om man setter href eller onClick

2024-03-12 08:00 UTC, HeleneKassandra commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Derfor href og onClick er satt som props og ikke bare som en del av ...rest

2024-03-12 08:03 UTC, HeleneKassandra commented on packages/ffe-cards/less/detail-list-card.less
> +        grid-template-columns: 1fr 2fr;
Hva mener du? Jeg prøvde å zoome og har hatt liten skjermstørrelse og det funker for meg? Utenom at det blir veldig mange linjer.  Jeg valgte grid over flex fordi jeg ville kontrollere størrelsen på hver kolonne, sånn at "verdi" får større plass og derfor knekker over flere linjer senere.

2024-03-12 08:06 UTC, HeleneKassandra commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
href:  role = link
onClick: role = button

2024-03-12 08:24 UTC, HeleneKassandra commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Kan også gjøre det til native elements, der man kan sende med om det skal være a eller button-element? 
Grunnen til at jeg ikke gjorde det var fordi jeg håpet å slippe unna å overskrive styling for å slippe unna default styling på f.eks knapp.

2024-03-12 08:26 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Jag er veldig skeptisk til att dette er riktig/lurt. Må bruke data-href da? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role
![image](https://github.com/SpareBank1/designsystem/assets/2248579/17558566-35aa-49da-a852-682bf8d652c0)

En annen ting. Vad hvis man trenger en onCklick på lenke før tracking feks. Alltså ikke bare button. Hvis man landar på det her burde man ta in element istellet kanskje istelelt for att beregna det?

element?: "a" | "button"

Men da har man vell problemet att dom olika komponenterna trenger forskjelliga props



Hvis jag sender in både onClick og href nå så får jag en button med en href på?

2024-03-12 08:31 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +        grid-template-columns: 1fr 2fr;
Så lenge du testet så ær det fint.. også velldig lange ord så att dom brekker. 
```
overflow-wrap: anywhere;
```

Er med noe sted eller erves?

2024-03-12 08:37 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Men nor sånt da kanskej kan funke
```
  <dl>
        <div role="link" data-href="#" tabIndex={0}>
            <dt>1</dt>
            <dd>1</dd>
        </div>
    </dl>
```
    
Hvis man klarer og finne ut av når det er knapp og når det er en linke. Utfordrande og typa gott også. Kanske ha en DetailListCardItemLink, DetailListCardItem og en DetailListCardButton? i API?

2024-03-12 08:39 UTC, pethel commented on packages/ffe-cards/less/theme.less
> +            --ffe-v-detail-list-card-background-color: #1c1c1c;
Er denne fargen  i designsystemet?

2024-03-12 08:49 UTC, pethel commented on packages/ffe-cards/less/theme.less
> +            --ffe-v-detail-list-card-background-color: #1c1c1c;
--ffe-grey-charcoal-darkmode var det visst

2024-03-12 08:50 UTC, pethel commented on packages/ffe-cards/less/detail-list-card.less
> +            &:focus-visible {
Vi ønsker kun  &:focus-visible ?

2024-03-12 08:53 UTC, pethel commented on packages/ffe-cards-react/src/DetailListCard/DetailListCardItem.js
> +    /** href on row - if set role is set to link*/
Intressant hvordan en skjermleser vill taklet dette også før det blir ju som førsta jag limat in før den. Når man endrer role her påverkar man ju elementerna runtomkring. parent iaf.

2024-03-12 11:20 UTC, HeleneKassandra commented on packages/ffe-cards/less/theme.less
> +            --ffe-v-detail-list-card-background-color: #1c1c1c;
Ja, det er egentlig ikke en farge vi bruker lenger, men det er ingen farger i nåværende palett som funker helt optimalt

2024-03-12 11:20 UTC, HeleneKassandra commented
Denne er forsatt WIP! Men setter den til "ready for review" sånn at Andrea og Sindre kan teste UU via Azure / Component-overview

2024-03-13 12:32 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCard.js
> +DetailListCard.defaultProps = {};
Kan droppes?

2024-03-18 12:32 UTC, antidecaf commented on packages/ffe-lists/less/detail-list-card.less
> +        &--clickable {
100% pirk, men jeg ønsker meg en transition på hover slik at effekten ikke blir så brå. :)
Kan fikses i full fart ved å legge inn denne linja i `&--clickable`:

`transition: box-shadow var(--ffe-transition-duration) var(--ffe-ease);`

2024-03-21 12:28 UTC, pethel requested changes

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCardItem.js
> +const DetailListCardItem = props => {
const DetailListCardItem = ({ className, label, value, ...rest }) => {

Vorfor ikke bare sånn med en gang?

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCardItem.js
> +            className={classNames('ffe-detail-list-card__item', className)}
Burde man ha mulighet att senda en ref till denne hvis man sender en lenke i label/value og ønsker gjøra hele raden klickbar akkurat som du var inne på i starten når denne PR først ble laget?

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCardItem.js
> +    label: oneOfType([node, string]).isRequired,
![image](https://github.com/SpareBank1/designsystem/assets/2248579/30e2a137-aed0-480b-973f-eb73f7ef2dce)
Kan nok trygt fjerne string herifra

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCard.spec.js
> +        expect(wrapper.exists()).toBe(true);
Denne `expect(wrapper.exists()).toBe(true); ` blir vell overflødig. Hvis denne er false vil aldrig linjen under pasera testen

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCard.spec.js
> +        const wrapper = getDetailListCardItemWrapper({ href: '#' });
Bruke noe som faktiskt er lov att ha på en div? id feks?

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCard.spec.js
> +        expect(wrapper.find('dt').exists()).toBe(true);
droppe denne? `expect(wrapper.find('dt').exists()).toBe(true);` linjen under tester ju også dette

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/DetailListCard.spec.js
> +        expect(wrapper.find('dd').exists()).toBe(true);
droppe denne? ` expect(wrapper.find('dd').exists()).toBe(true);` linjen under tester ju også dette

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/index.d.ts
> +    label: React.ReactNode;
Er ikke gjort ellers men man kunde kanskje vurdert `NonNullable<React.ReactNode>`, eftersom null/undefined også er ReactNode

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/index.d.ts
> +export interface DetailListCardItemProps {
Hvis vi kan gjør slik så kan vi dropppe className før den kommer med i `React.ComponentPropsWithoutRef<'div'>`. Man får også med id og alt annet som er lov på en div. Jag tok WithoutRef eftersom du ikke har det i implementasjonen og da vil man få feil hvis man provar senda det med.
```
export interface DetailListCardItemProps  extends React.ComponentPropsWithoutRef<'div'> { 
    label: React.ReactNode;  // vurder NonNullable
    value: React.ReactNode; // vurder NonNullable
}
```

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists-react/src/index.d.ts
> +export interface DetailListCard {
Vad med sånn?
```
export interface DetailListCard  extends React.ComponentPropsWithoutRef<'dl'> { 
   children:
        | React.ReactNode
        | ((props: DetailListCardItemProps) => React.ReactNode);
}
```

2024-03-21 12:28 UTC, pethel commented on packages/ffe-lists/less/detail-list-card.less
> +        @media (max-width: 299px) {
Vad kommer 299? 
Jag tror man heller burde bruke container queries her. Si att jag har 3 kolumner på desktop med en slik liste i varje kolkume. Da ønsker jag responsive visning. 

container queries har bra støtte nu
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries

2024-03-21 14:19 UTC, HeleneKassandra commented on packages/ffe-lists-react/src/DetailListCardItem.js
> +            className={classNames('ffe-detail-list-card__item', className)}
I utgangspunktet så tenker jeg at det er fint hvis vi kan standardisere ting, sånn at ikke noen steder er hele raden klikkbar og andre steder ikke.

2024-03-21 15:15 UTC, HeleneKassandra commented on packages/ffe-lists/less/detail-list-card.less
> +        @media (max-width: 299px) {
Jeg får feil i editoren når jeg skriver container, så litt usikker på om det er less, editoren min eller eslint som trenger en oppdatering?

2024-03-21 15:15 UTC, HeleneKassandra commented on packages/ffe-lists/less/detail-list-card.less
> +        @media (max-width: 299px) {
"unknown rule at @container"

2024-03-22 07:01 UTC, pethel commented on packages/ffe-lists/less/detail-list-card.less
> +        @media (max-width: 299px) {
Kan det vare noe med less version eller noen instilling eller så? Det burde vare noe vi kunde slått på
https://caniuse.com/css-container-queries
Men dette gjelder vell i så fall flere komponenter. Muligheterna kan vell utforskas i en egen opgave kanskje?

2024-03-22 11:37 UTC, HeleneKassandra commented on packages/ffe-lists/less/detail-list-card.less
> +        @media (max-width: 299px) {
Kan være editoren, for npm run kjørte fint. Så lagt inn nå

2024-03-22 13:39 UTC, pethel commented on packages/ffe-lists-react/src/index.d.ts
> +        | NonNullable<React.ReactNode>
Fint att du provar ut NonNullable<React.ReactNode>. Vi får se hvordan det oppleves.

2024-03-22 13:39 UTC, pethel commented on packages/ffe-lists/less/detail-list-card.less
> +        @container (width < 299px) {
Veldig fint at du fikk det til at fungere.

2024-03-22 13:40 UTC, pethel approved these changes
Ser br aut før meg nå!

2024-03-23 08:52 UTC, pethel reviewed
Commitsen burde vell også ryddas op i. En commit per pakke

2024-03-25 10:54 UTC, merged