build(ffe-icons): create destination directory if needed
SpareBank1/designsystem pull request #221
Opened 2018-05-03 14:07 UTC by henrikhermansen

This commit makes `ffe-icons` able to create destination directory when
building icons, if it is missing.

2018-05-03 14:34 UTC, wkillerud submitted a review, later dismissed

2018-05-03 14:34 UTC, wkillerud commented on packages/ffe-icons/bin/build.js
> +if (!fs.existsSync(options.dest)) {
`mkdir -p` does nothing if the directory exists, so this check can be removed.

2018-05-03 14:41 UTC, henrikhermansen commented
@wkillerud I amended the initial commit and re-added the merge from develop. Your requested changes should be done now :slightly_smiling_face:

2018-05-04 06:24 UTC, selbekk requested changes

2018-05-04 06:24 UTC, selbekk commented on packages/ffe-icons/bin/build.js
> +});
As far as I can see from [the docs](https://github.com/substack/node-mkdirp#mkdirpsyncdir-opts), `mkdirp` doesn't accept a function as a second argument. Actually, [looking at the source code](https://github.com/substack/node-mkdirp/blob/master/index.js#L56-L58), it looks like if the second argument isn't an object, it sets the second argument as the `mode` argument - which will potentially bork your access rights.

I suggest that you either just drop the second argument:

```js
mkdirp.sync(options.dest);
```
, or do the same, but add error handling (not sure how real of an issue that will ever be) and a proper error message (and error code) to describe what happened :)

2018-05-04 06:29 UTC, ivarni commented on packages/ffe-icons/bin/build.js
> +});
I was actually puzzled by why a synchronous function would accept a callback but just figured the API was wierd :)

2018-05-04 06:30 UTC, henrikhermansen commented on packages/ffe-icons/bin/build.js
> +});
Hmm indeed, so it seems.
I actually took this from [a different part of the docs](https://github.com/substack/node-mkdirp#example). Maybe I should file an issue about his example :stuck_out_tongue: 
I'll fix this in a bit!

2018-05-04 06:32 UTC, ivarni commented on packages/ffe-icons/bin/build.js
> +});
Yeah, that's the async version. It makes sense for that to take a callback.

2018-05-04 06:33 UTC, selbekk commented on packages/ffe-icons/bin/build.js
> +});
@henrikhermansen that part's correct though - if you want to use the asynchronous version, you need to pass a function as a callback. The sync version should probably come with its own example in the docs.

2018-05-04 07:25 UTC, henrikhermansen commented on packages/ffe-icons/bin/build.js
> +});
You guys are right! I'm being a total noob right now :man_facepalming:

2018-05-04 07:45 UTC, henrikhermansen commented on packages/ffe-icons/bin/build.js
> +});
@selbekk I simply removed the callback as second argument.

2018-05-04 08:33 UTC, selbekk approved these changes

2018-05-04 08:35 UTC, merged