Develop fjern colored bg
SpareBank1/designsystem pull request #2291
Opened 2024-09-12 08:08 UTC by pethel

Fjerner onColoredBg .. tror vi bare må lage en version av den der det er støtett fordi props på sendes osv. Fikk også fonterna att funka med inline

2024-09-12 08:21 UTC, antidecaf requested changes
Fontene bør vel helst ikke slettes?

2024-09-12 08:50 UTC, pethel commented
> Fontene bør vel helst ikke slettes?

Dom er inline nu istellet. Det så ut att funka.

2024-09-12 08:56 UTC, antidecaf commented
> Dom er inline nu istellet. Det så ut att funka. Vi trenger ikek ha dom inline kanskje? Cache og sånt?

Men de kan vel fortsatt ikke slettes fra ffe-webfonts? Da brekker jo sb1-fonts.less helt?

2024-09-12 09:29 UTC, pethel commented
> > Dom er inline nu istellet. Det så ut att funka. Vi trenger ikek ha dom inline kanskje? Cache og sånt?
> 
> Men de kan vel fortsatt ikke slettes fra ffe-webfonts? Da brekker jo sb1-fonts.less helt?

Men den filen har vi vell inget forhold til lenger?

2024-09-12 09:39 UTC, antidecaf commented
> Men den filen har vi vell inget forhold til lenger?

ffe-webfonts er fortsatt en [pakke som er tilgjengelig via npmjs](https://www.npmjs.com/package/@sb1/ffe-webfonts) og som lastes ned mellom 200 og 300 ganger i uka derfra og vi vet ikke hvordan den brukes overalt. I beste fall er slettingen en breaking change som burde markeres som det i en egen commit, men vi kan i alle fall ikke slette fonts-mappa uten videre.

2024-09-12 09:45 UTC, pethel commented
> > Men den filen har vi vell inget forhold til lenger?
> 
> ffe-webfonts er fortsatt en [pakke som er tilgjengelig via npmjs](https://www.npmjs.com/package/@sb1/ffe-webfonts) og som lastes ned mellom 200 og 300 ganger i uka derfra og vi vet ikke hvordan den brukes overalt. I beste fall er slettingen en breaking change som burde markeres som det i en egen commit, men vi kan i alle fall ikke slette fonts-mappa uten videre.

Hahah nu ser jag... jag slettet feil filer. mente rog slette dom i public/fonts som vi
 brukte

2024-09-12 09:54 UTC, pethel commented
> > Men den filen har vi vell inget forhold til lenger?
> 
> ffe-webfonts er fortsatt en [pakke som er tilgjengelig via npmjs](https://www.npmjs.com/package/@sb1/ffe-webfonts) og som lastes ned mellom 200 og 300 ganger i uka derfra og vi vet ikke hvordan den brukes overalt. I beste fall er slettingen en breaking change som burde markeres som det i en egen commit, men vi kan i alle fall ikke slette fonts-mappa uten videre.

Sånn! Nå har jag sletet rikig sted!

2024-09-12 10:26 UTC, antidecaf commented
> Sånn! Nå har jag sletet rikig sted!

Topp! Da gjenstår det bare å finne ut hvorfor lintingen klager på postcss-less i byggene på de siste PR-ene. :no_mouth:

2024-09-16 10:43 UTC, antidecaf approved these changes

2024-09-16 11:02 UTC, merged