docs(ffe-buttons-react): legger til stories for knapper
SpareBank1/designsystem pull request #2298
Opened 2024-09-17 11:40 UTC by antidecaf

Stories for knappekomponentene

2024-09-17 11:47 UTC, pethel commented on packages/ffe-buttons-react/src/ActionButton.stories.tsx
> +        <ButtonGroup {...args}>
args burde gå på ActionButton og ikke ButtonGroup vell?

2024-09-17 11:48 UTC, pethel commented on packages/ffe-buttons-react/src/ExpandButton.stories.tsx
> +            <>
```suggestion

```

2024-09-17 11:52 UTC, pethel requested changes

2024-09-17 11:52 UTC, pethel commented on packages/ffe-buttons-react/src/InlineExpandButton.stories.tsx
> +                    <InlineExpandButton
skall det ikke noen args på knappen her? {...args} slik att man kan teste olika.

2024-09-17 11:52 UTC, pethel commented on packages/ffe-buttons-react/src/PrimaryButton.stories.tsx
> +            <PrimaryButton>Primærknapp</PrimaryButton>
Burd edet ikke bare vart en primærknapp her også får den {..args} slik att man kan teste? Nu går ting på buttonGroup?

2024-09-17 11:52 UTC, pethel commented on packages/ffe-buttons-react/src/TaskButton.stories.tsx
> +        const addIcon =
Hvi trenger ikke gjøre slik lenger nå va?

2024-09-17 12:03 UTC, antidecaf commented on packages/ffe-buttons-react/src/ActionButton.stories.tsx
> +        <ButtonGroup {...args}>
Nei du har rett. Litt halvhjertet klipp og lim her

2024-09-17 12:09 UTC, antidecaf commented on packages/ffe-buttons-react/src/TaskButton.stories.tsx
> +        const addIcon =
Kan du utdype? Jeg skjønner ikke helt hva du mener

2024-09-17 13:15 UTC, pethel commented on packages/ffe-buttons-react/src/TaskButton.stories.tsx
> +        const addIcon =
Beklager..  man kan importera svg nå istellet før att inlina? typ slik
```
import { Icon } from '@sb1/ffe-icons-react';
import closeIcon from '@sb1/ffe-icons/icons/open/300/md/close.svg';


...

 icon={<Icon fileUrl={closeIcon} size="md" />}
```

Kanske er utanfør scope?

2024-09-17 13:31 UTC, antidecaf commented on packages/ffe-buttons-react/src/TaskButton.stories.tsx
> +        const addIcon =
Ah ja, enig i det. Det er hakket enklere.

2024-09-17 13:42 UTC, pethel submitted a review, later dismissed

2024-09-18 12:11 UTC, pethel commented on packages/ffe-buttons-react/src/BackButton.stories.tsx
> +    render: args => <BackButton onClick={f => f}>Tilbake</BackButton>,
?
```suggestion
    render: args => <BackButton {...args}>Tilbake</BackButton>,
```

2024-09-18 12:11 UTC, pethel commented on packages/ffe-buttons-react/src/ActionButton.stories.tsx
> +            <ActionButton {...args} onClick={f => f}>
?
```suggestion
            <ActionButton {...args} >
```

2024-09-18 12:13 UTC, pethel approved these changes, later dismissed

2024-09-18 12:46 UTC, merged