Update colors and color docs
SpareBank1/designsystem pull request #238
Opened 2018-05-16 12:29 UTC by antidecaf

This commit makes adjustments to the color palette as well as updates to the documentation of colors, as described in #80:

* Updated color names with ones used by marketing/design, in addition to Less variable names
* Restructured color categories
* Split color documentation into separate overview and usage sections
* Added visibility toggling of said sections

In `/packages/ffe-core`:
* Added `@ffe-grey-warm`
* Deprecated `@ffe-blue-deep-sky` and `@ffe-sand-ivory`

2018-05-16 12:43 UTC, selbekk submitted a review, later dismissed

2018-05-16 14:13 UTC, wkillerud requested changes
> add new color

Sounds like a `feat`, but is tagged as a `fix`.

2018-05-16 14:13 UTC, wkillerud commented on packages/ffe-core/less/colors.less
> +@ffe-sand-ivory: #FBFAF5; // Deprecated 05.2018
I'd like a "use X instead" after the deprecation notices, and a blank new line at the EOF.

2018-05-16 14:13 UTC, wkillerud commented on src/assets/sds.js
> +            var section = document.querySelector("."+sectionId);
Pet peeve: mixing `'` and `"` as string delimiters.

2018-05-16 14:13 UTC, wkillerud commented on src/styles/examples/color.less
> +}
Missing blank line at EOF.

2018-05-16 14:13 UTC, wkillerud commented on styleguide-content/visuell-identitet/farger.md
> +        Det er utviklet en egen fargepalett for det digitale rammeverket. Fargepaletten er basert på SpareBank 1 sin visuelle identitet og skal være med på å bidra til en konsistent opplevelse på tve
```diff
- tvers av alle digitale flager
+ tvers av alle digitale flater
```

2018-05-16 14:13 UTC, wkillerud commented on src/styles/examples/color.less
> +        border: 1px solid @ffe-grey-silver;
We use `box-sizing: border-box`, so this colors box will be 4 * 1px larger than the others unless they also get a border. I think the border can be `1px solid transparent` though, if you don't want color there.

2018-05-16 14:13 UTC, wkillerud commented on styleguide-content/visuell-identitet/farger.md
> +            <div>#FFFFFF<br/>@ffe-white</div>
Hvit is also listed under Bakgrunnsfarger GUI. Is that intentional? Seems like the only one that has two listings.

2018-05-16 14:52 UTC, antidecaf commented on styleguide-content/visuell-identitet/farger.md
> +            <div>#FFFFFF<br/>@ffe-white</div>
Not sure if it's intentional or not, but it's listed twice in the sketches. It is used in the context of both categories, anyway.

2018-05-16 15:16 UTC, antidecaf commented
@wkillerud Thanks for your comments. I've made changes to follow up on those I haven't replied to directly.

2018-05-22 06:30 UTC, selbekk approved these changes

2018-05-22 08:14 UTC, wkillerud commented
LGTM :smiley:

2018-05-22 08:14 UTC, wkillerud approved these changes

2018-05-22 08:27 UTC, merged