refactor(ffe-core): ny fargepalett med semantiske variabler.
SpareBank1/designsystem pull request #2406
Opened 2024-11-04 10:15 UTC by tuva-odegard

Den nye fargepalletten som designerne har jobbet med en god stund. 
Leter etter en god måte å organisere less vs css vs dark mode på.

2024-11-04 10:17 UTC, pethel commented
feat(ffe-core): ny fargepalett med semantiske variabler.

2024-11-04 10:42 UTC, antidecaf requested changes

2024-11-04 10:42 UTC, antidecaf commented on packages/ffe-core/less/theme.less
> +            --ffe-color-surface-critical-default: var(--ffe-color-bær-850);
Variablene bør bruke `ae` og ikke `æ`.

2024-11-04 10:42 UTC, antidecaf commented on packages/ffe-core/less/theme.less
> +    /* End depricated */
```suggestion
    /* End deprecated */
```

2024-11-04 10:42 UTC, antidecaf commented on packages/ffe-core/less/theme.less
> +    /* DEPRICATED */
```suggestion
    /* DEPRECATED */
```

2024-11-04 10:42 UTC, antidecaf commented on packages/ffe-core/less/theme.less
> +            --ffe-color-background-default: var(--ffe-color-graa-1000);
Disse css-variablene ser ikke ut til å finnes, fargene er kun definert i Less. Så for at dette skal funke må alle less-variablene oversettes til css i theme.less slik det var gjort tidligere. :)

2024-11-05 07:40 UTC, pethel approved these changes, later dismissed

2024-11-05 08:37 UTC, antidecaf submitted a review, later dismissed

2025-01-20 08:40 UTC, closed without merging