feat(ffe-header): Add new styling of header.
SpareBank1/designsystem pull request #2441
Opened 2024-12-09 13:55 UTC by henninghalvsb1

Redirect to Profile page when clicking on users name or icon instead of dropdown menu. Switch places of hamburger menu and user icon.
Add logout button to hamburger menu instead of user menu. This is an optin feature, the old version still works.

-----

Oppdatere styling av FFE-header i henhold til skisser

## Beskrivelse
Vi ønsker å gjøre en endring i header slik at når man klikker på navnet sitt / brukerikonet så blir man sendt til Profil.
Vi har tatt en runde med designere for å få dette avklart, og vi har også bestemt å bytte plass på site navigation og user navigation (som nå går til profil). Dette er for å plassere inngangen til profil på samme sted som i mobilbanken. 

## Motivasjon og kontekst
Ønsker å tilgjengeligjøre Profil på desktop på en god måte.

## Testing
Testet via Storybook, har kodet opp et eget eksempel. Vi har lagt inn en toggle så man kan raskt switche mellom dagens situasjon og det nye som er foreslått.

2024-12-09 14:39 UTC, pethel requested changes

2024-12-09 14:39 UTC, pethel commented on packages/ffe-header/less/ffe-header.less
> +                order: 2;
Slik jag førstår det du gjør her så kastar du om rekkefolge på elementer som kan ha fokus. Det er ikke lurt UU messig. Blir forvirrande. Hvis jag ikke missførstår det du gjør her.

2024-12-09 14:44 UTC, pethel commented on packages/ffe-header/less/ffe-header.less
> +                    color: var(--ffe-farge-fjell);
Funker disse fargerna på darkmode?

2024-12-09 15:04 UTC, pethel commented
Tusen takk før pull request

2024-12-10 08:05 UTC, henninghalvsb1 commented on packages/ffe-header/less/ffe-header.less
> +                    color: var(--ffe-farge-fjell);
Skal ta en kikk! Ikke testet med darkmode.

2024-12-10 08:05 UTC, henninghalvsb1 commented on packages/ffe-header/less/ffe-header.less
> +                order: 2;
Skal sjekke ut hvordan det blir med tabbing osv.

2024-12-10 08:14 UTC, kwltrs commented on packages/ffe-header/less/ffe-header.less
> +                    color: var(--ffe-farge-fjell);
ffe-header har ikke darkmode.

2024-12-11 12:04 UTC, henninghalvsb1 commented on packages/ffe-header/less/ffe-header.less
> +                order: 2;
@kwltrs har rullet tilbake dette, det var ikke kritisk

2024-12-11 14:32 UTC, kwltrs commented on packages/ffe-header/less/ffe-header.less
> +                    color: var(--ffe-farge-fjell);
Det ble nå ikke noe fargeendringer.

2024-12-12 08:10 UTC, pethel commented on packages/ffe-header/less/ffe-header.less
> +    .ffe-header--enable-link-to-profile {
Hvis får dere en advarsel her av stylelint  på før dyp selector? jag tror 3 klasser er maks og her er 4? Det er greit hvis dere må ha det men legge på en kommentar da kanske slik att warningen ikke bli synlig.

2024-12-12 08:13 UTC, pethel approved these changes
Koden ser fint ut før meg, Sålenge dere er eniga med designerna på teamet vårt så ær dette greit før meg.

2024-12-12 09:55 UTC, merged