fix(ffe-account-selector-react): fixed accessibility errors
SpareBank1/designsystem pull request #258
Opened 2018-05-25 13:22 UTC by eksb1

2018-05-25 13:25 UTC, eksb1 commented
How do I link  pull request to issue?

2018-05-25 13:52 UTC, wkillerud commented
You can link to an issue (or PR) by typing `#` and the issue (or PR) number in a comment. Github will create a link. So `#244` becomes #244 :rocket:

2018-05-25 14:04 UTC, wkillerud requested changes
The labels should use texts from the language files and follow the `locale` prop.

2018-05-25 14:04 UTC, wkillerud commented on packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js
> +                        aria-label="reset"
This text will be read out loud by screen readers and should follow the same language settings as the rest of the component. If you look in the [i18n](https://github.com/SpareBank1/designsystem/tree/develop/packages/ffe-account-selector-react/src/i18n) folder you'll find the languages and texts that are being used in the component. `RESET_SEARCH` looks promising to use here, and the label for the expand/collapse button could perhaps use `ACCOUNTSLIST_OPEN` and `ACCOUNTSLIST_CLOSE` depending on state? 

The [AccountNoMatch](https://github.com/SpareBank1/designsystem/blob/36dc3a255a300b3639b727ccdef8729c24a6a036/packages/ffe-account-selector-react/src/subcomponents/account/AccountNoMatch.js) component has an example on how to use the language file. You need to know the current `locale` though, which `Input` doesn't right now. From what I can see `Input` is only used from `BaseSelector`. `BaseSelector` gets the `locale` prop from `AccountSelector` and `AccountSelectorMulti`, it's just not used/listed in `propTypes`. So if you send the `locale` prop from `BaseSelector` to `Input` and use the language file this should be good to go :)

2018-05-28 09:04 UTC, eksb1 commented
#244

2018-05-28 15:14 UTC, eksb1 commented
@wkillerud could you please review again?

2018-05-29 07:27 UTC, selbekk approved these changes
LGTM! Great work!

2018-05-29 07:29 UTC, wkillerud approved these changes
LGTM, thanks for making the changes! :)

2018-05-29 07:29 UTC, wkillerud commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js
> +                    locale={locale}
Just for reference in case others are wondering: `AccountSelectorMulti` already passed on `locale`

2018-05-29 07:34 UTC, merged