feat(ffe-icons): Add mobil-snakkeboble ikon
SpareBank1/designsystem pull request #259
Opened 2018-05-28 12:40 UTC by ivarni

2018-05-28 12:41 UTC, ivarni commented on packages/ffe-icons/README.md
> -10. Create a pull request from your repos feature branch to ffe-icons `master`.
Fjernet disse linjene siden de ikke virket veldig relevant lenger

2018-05-29 07:36 UTC, wkillerud requested changes

2018-05-29 07:36 UTC, wkillerud commented on packages/ffe-icons/icons/mobil-snakkeboble-ikon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="37 38 103 105"><path d="M129.25 70c0 5.7-4.63 10.32-10.32 10.32h-7.5l-1.82 1.54-13.48 11.39V80.32h-6.5A10.3 10.3 0 0 1 79.38 70V54.68c0-5.7 4.63-10.33
Ikonene skal helst ikke ha en inlinet `fill`, så vi får overstyrt med CSS.

2018-05-29 07:49 UTC, ivarni commented on packages/ffe-icons/icons/mobil-snakkeboble-ikon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="37 38 103 105"><path d="M129.25 70c0 5.7-4.63 10.32-10.32 10.32h-7.5l-1.82 1.54-13.48 11.39V80.32h-6.5A10.3 10.3 0 0 1 79.38 70V54.68c0-5.7 4.63-10.33
oooops 😨

2018-05-29 08:26 UTC, wkillerud approved these changes

2018-05-29 08:33 UTC, merged