feat(ffe-datepicker-react): Add id prop
SpareBank1/designsystem pull request #267
Opened 2018-05-31 14:44 UTC by selbekk

This commit passes the id prop to the input field, so that it's easier
to pass the ID to the correct components.

2018-05-31 17:55 UTC, wkillerud commented
> It does NOT auto-generate an ID if one isn't provided. That should be its own discussion imo.

Apart from bundle size, are there any downsides to generate a random working ID to help developers with a11y?

2018-05-31 17:57 UTC, wkillerud approved these changes

2018-05-31 18:13 UTC, wkillerud requested changes
On second thought - the [`label` element needs an updated `htmlFor`](https://github.com/SpareBank1/designsystem/blob/0e8ebe96e8cf0d8511a2f0c98ca8765657194d4d/packages/ffe-datepicker-react/src/datepicker/Datepicker.js#L312) that also checks for `this.props.id`, otherwise this should have no effect.

2018-06-01 05:47 UTC, ivarni commented
But.. it already does this?
[id is already part of inputProps](https://github.com/SpareBank1/designsystem/blob/31c28f6769240e43567535e80096358d7f6f7a25/packages/ffe-datepicker-react/src/datepicker/Datepicker.js#L388) and it gets [destructured and passed to <input>](https://github.com/SpareBank1/designsystem/blob/31c28f6769240e43567535e80096358d7f6f7a25/packages/ffe-datepicker-react/src/input/Input.js#L45) already?

I'm all for getting rid of these `inputProps` objects where we can but I'd prefer we don't duplicate them :)

2018-06-01 06:01 UTC, ivarni commented
Also, auto-generating an id would not affect the bundle size since [it's already done for the label](https://github.com/SpareBank1/designsystem/blob/31c28f6769240e43567535e80096358d7f6f7a25/packages/ffe-datepicker-react/src/datepicker/Datepicker.js#L27) :)

2018-06-01 07:53 UTC, wkillerud commented
> But.. it already does this? id is already part of inputProps and it gets destructured and passed to the input already?

Yes, but the API is kind of clunky. I also mentioned in the issue how it was confusing that if I give the component a `label` prop I had to provide an ID (especially an `inputProps.id`) to get proper linkage between the label and the input field. The PR doesn't address that yet though.

2018-06-01 07:55 UTC, ivarni commented
But now we're going to be able to provide an `id` through two different means? I'm not sure how that makes anything less confusing :)

2018-10-23 05:37 UTC, selbekk commented
Closing this since abandoned.

2018-10-23 05:37 UTC, closed without merging