fix(ffe-core): Visual indication on left menu
SpareBank1/designsystem pull request #430
Opened 2018-09-26 21:19 UTC by pethel

Solves: https://github.com/SpareBank1/designsystem/issues/324

2018-09-27 10:02 UTC, antidecaf commented on src/components/components-list/ComponentsListRenderer.js
> -                            'sb1ds-components-list__link--heading': heading,
This line should be added back.

2018-09-27 10:02 UTC, antidecaf requested changes
Thanks for the PR! Everything looks good, just needs a couple of minor changes:

* The commit message indicates a change in `ffe-core`, but there are no changes in that package. Thus, `fix(ffe-core):` should be rewritten to just `fix:`
* According to the description this PR solves #326, but the right issue number is #324.
* The `--heading` modifier has been removed from top level links in the sidebar - see separate comment. I think we need to keep that in place, even if the visual design is wrong (that can be fixed in a later PR when the look of the sidebar has been redesigned).

2018-09-27 18:03 UTC, pethel commented
Sorry about the confusion on issue number and commit message. Should be fixed now

2018-09-28 09:39 UTC, antidecaf approved these changes

2018-09-28 09:39 UTC, merged