fix(ffe-account-selector-react): Suggestions will now correctly lose …
SpareBank1/designsystem pull request #452
Opened 2018-10-06 21:15 UTC by simjes

…focus

The suggestion list will now close when AccountSelector lose focus after opening it by clicking the chevron

Fixes #435

2018-10-08 08:36 UTC, selbekk requested changes
Great job on this PR - especially with adding tests and what not.

I would love for the callback to refer to `this.props` instead of passing the value as an argument to the event handler - but that's the only change I can think of. Good stuff!

2018-10-08 08:36 UTC, selbekk commented on packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js
> +    onExpandOrCollapse(e, isSuggestionsShowing) {
Can you get this value from `this.props.isSuggestionsShowing` instead of passing it as an argument?

2018-10-08 15:25 UTC, simjes commented
@selbekk Updated :)

2018-10-09 05:08 UTC, selbekk approved these changes

2018-10-09 05:08 UTC, selbekk commented
So can you please explain to me why you're doing this instead of what we did previously? I'm not well enough versed with this code to understand its implications.

2018-10-09 13:39 UTC, antidecaf approved these changes

2018-10-09 15:37 UTC, simjes commented
e.preventDefault() will prevent focus being set on an element so the onBlur() would not fire when clicking outside the inputField component.
Instead I put focus on the input element when you click the button. Setting focus on the button itself would also work, but there would be a border on the button and I didn’t want to change the style.

I can’t remember what it was, but there was another issue with putting focus on the button.

2018-10-10 05:56 UTC, merged

2018-10-10 05:56 UTC, selbekk commented
Thanks for the explanation @simjes :+1: and thank you for your first contribution!