feat(ffe-tables-react): Migrate from deprecated componentWillReceiveP…
SpareBank1/designsystem pull request #466
Opened 2018-10-20 15:04 UTC by simjes

This is a suggested solution for #372 for ffe-tables-react. I am not sure if this is the best way to solve it, especially  for the SortableTable, see: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html. “If you’re updating derived state unconditionally or updating it whenever props and state don’t match, your component likely resets its state too frequently”.

I am open for suggestions for how to improve this solution.

2018-10-22 07:27 UTC, selbekk approved these changes

2018-12-06 12:30 UTC, henrikhermansen submitted a review, later dismissed
This component SortableTable is quite complex. I see we do have a shouldComponentUpdate, so I guess using derived state isn't too bad here.

This commit will just party fix #372 as it only changes ffe-tabls-react, right? Or has the other packages been handled already?

2018-12-06 19:47 UTC, simjes commented
Yes, this is only a partial fix for #372.  #369 covered one of the other ones, but `ffe-datepicker-react` and `ffe-decorators-react` are still missing

2018-12-07 07:43 UTC, selbekk requested changes

2018-12-07 07:43 UTC, selbekk commented on packages/ffe-tables-react/src/SortableTable/SortableTable.js
> +                props: nextProps,
This is a pragmatic way of doing things, but I think we can do even better. Saving all the previous props in state seems like an anti-pattern we can avoid.

Perhaps we can memoize the `sortData` method, and call it on every render? This way we can omit keeping the sorted table data in state as well! 

You can read more about this approach in the ["You might not need derived state"](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization) blog post by the React team.

2018-12-11 09:41 UTC, simjes commented
Updated @selbekk

2018-12-11 10:06 UTC, selbekk approved these changes
That looks god damn amazing. :tada: :100:

2018-12-11 10:06 UTC, merged