Add toggle switch component
SpareBank1/designsystem pull request #527
Opened 2018-11-27 15:08 UTC by antidecaf

This PR adds a new toggle switch component. It looks like this:

Default:
![image](https://user-images.githubusercontent.com/463847/49089997-1865b880-f25d-11e8-9832-4c7b97e9acc9.png)

Selected:
![image](https://user-images.githubusercontent.com/463847/49090042-2d424c00-f25d-11e8-8c9d-c07775930ddb.png)

**It's not yet decided whether or not this will be merged.** Some questions have arisen along the way and need to be answered first:

- Does the toggle switch pattern make sense in a desktop UI? This component renders a switch on any screen size. Should the switch in stead be replaced by a different pattern on large screens, and if so, which one?

- Guidelines are not yet written, but should be if this is to be merged. When to use a toggle switch vs radio buttons/checkboxes should be very clear. According to [NN Group guidelines](https://www.nngroup.com/articles/toggle-switch-guidelines/) the toggle switch pattern demands immediate results, i.e. they should not be used in forms that require users to click a button for changes to take effect. Any input on this? Anything else?

- How to handle the focus state? This implementation includes the regular focus outline (same one used in form elements), but it feels a bit off given that switches generally don't have an outline in a native mobile context. Do we:

1. Keep it as is?
2. Show the outline only on large screens?
3. Remove the outline altogether? (If so, what consequenses does it have for accessibility?)

- How about the hover state? I've added the focus style on hover for now.

Hover/focus state:
![image](https://user-images.githubusercontent.com/463847/49090300-b2c5fc00-f25d-11e8-860f-f3b1d8e3e493.png)
![image](https://user-images.githubusercontent.com/463847/49090315-b78ab000-f25d-11e8-8fef-ebd01486dd87.png)

Any input is welcome!

2018-11-28 07:08 UTC, ivarni commented
I don't think focus-states are very relevant on mobile? I'm not even sure how I focus an input control without triggering it on my phone. Or are there accessibility tools out there that rely on focus styling?

2018-11-28 09:05 UTC, selbekk requested changes
All in all, this looks very good! Should we also add some usage information, like when this is a good choice over the very similar RadioSwitch?

2018-11-28 09:05 UTC, selbekk commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    const id = props.id || `toggle-${hash()}`;
This will receive a new ID on each render. Instead, use a class component, and set the ID as an instance variable

2018-11-28 09:05 UTC, selbekk commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    right: bool,
perhaps `alignRight` is a more descriptive name?

2018-11-28 09:05 UTC, selbekk commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    right: bool,
Also - `id` is missing from the propTypes.

2018-11-28 09:05 UTC, selbekk commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    right: bool,
Also also - should `value` also be specified here? It's the main API to the component, could be nice to include in the docs?

2018-11-28 09:05 UTC, selbekk commented on packages/ffe-form-react/src/ToggleSwitch.md
> +    Abonner på ulidelig spennende oppdateringer
:joy:

2018-11-28 10:55 UTC, antidecaf commented
> I don't think focus-states are very relevant on mobile? I'm not even sure how I focus an input control without triggering it on my phone. Or are there accessibility tools out there that rely on focus styling?

You're right, it's mainly an issue in desktop browsers. But on a second glance it looks less weird than anticipated with the hover state that is identical to the focus state.

2018-11-28 11:02 UTC, antidecaf commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    right: bool,
Will fix!

2018-11-28 11:02 UTC, antidecaf commented on packages/ffe-form-react/src/ToggleSwitch.js
> +    const id = props.id || `toggle-${hash()}`;
Will fix!

2018-11-28 11:08 UTC, antidecaf commented
> Should we also add some usage information, like when this is a good choice over the very similar RadioSwitch?

Yes, as mentioned in the original comment, guidelines need to be added before this is merged. I'm not sure what exactly to add however, so I'll await some feedback from UX before doing any of that. :)

2018-11-28 13:35 UTC, kwltrs submitted a review, later dismissed

2018-12-06 11:19 UTC, hodoea requested changes
<img width="697" alt="skjermbilde 2018-12-07 kl 13 55 28" src="https://user-images.githubusercontent.com/8971560/49661633-d9e4b080-fa49-11e8-8671-a471bbaa6ccb.png">


Kan dette fungere som guidelines?

2018-12-06 11:31 UTC, selbekk commented
Veldig bra @hodoea ! Jeg savner fortsatt en differensiering mellom når man skal bruke en toggle vs en radio switch, though - kanskje verdt å nevne eksplisitt?

2018-12-06 12:07 UTC, hodoea commented
My two cents on these questions:

It's not yet decided whether or not this will be merged. Some questions have arisen along the way and need to be answered first:

Does the toggle switch pattern make sense in a desktop UI? This component renders a switch on any screen size. Should the switch in stead be replaced by a different pattern on large screens, and if so, which one?

**I am bit unsure here, I don`t see any problem with using this for desktop as long as we can convey to people how to best use this in the guidelines. This are some  examples from Google forms where you use a toggle-switch to "turn on" more features in your form. However I`ve mostly seen the use of toggle-switches for native functionalities (settings on your phone amongst others)** 

![screen recording 2018-12-06 at 12 59 pm](https://user-images.githubusercontent.com/8971560/49583021-23a09e80-f957-11e8-9f16-1c83bdc3737b.gif)

And another example:
![screen recording 2018-12-06 at 01 00 pm](https://user-images.githubusercontent.com/8971560/49583116-72e6cf00-f957-11e8-9b2f-9044249654fa.gif)

Guidelines are not yet written, but should be if this is to be merged. When to use a toggle switch vs radio buttons/checkboxes should be very clear. According to NN Group guidelines the toggle switch pattern demands immediate results, i.e. they should not be used in forms that require users to click a button for changes to take effect. Any input on this? Anything else?

How to handle the focus state? This implementation includes the regular focus outline (same one used in form elements), but it feels a bit off given that switches generally don't have an outline in a native mobile context. Do we:

Keep it as is?
Show the outline only on large screens?
**I propose we show the outline on large screens only if that is possible**
Remove the outline altogether? (If so, what consequenses does it have for accessibility?)

How about the hover state? I've added the focus style on hover for now.
**On mobile you do not have a hover state. I think perhaps this is one of the challenges if we use this component for both mobile and desktop.

2018-12-06 12:24 UTC, antidecaf commented
Yes, the hover/focus states are only present on large screens. Looks fine to me now:

![ezgif-1-ea1f06cdb031](https://user-images.githubusercontent.com/463847/49584017-39fc2980-f95a-11e8-98ea-9cb841c70b8e.gif)

I've added the guidelines, but won't merge the PR for now, as it has been decided that this component needs to be tested in an app first.

2018-12-06 12:46 UTC, hodoea commented
@selbekk hm.. I have not used this component before, and I read the little we have of guidelines for this. I dont see why we should use this over a radio button in our forms. I have raised this in our fora on Slack. One designer mentioned that they have many questions in their forms where they have used radio switches. Because of the components size the questions are "drowning" in the form. 

Where is a radio switch a very good use? Maybe anyone knows where the need for this come from.. ?

2018-12-06 13:07 UTC, antidecaf commented
The RadioSwitch component differs from ToggleSwitch in that it has no default value, and is used as a part of longer forms with submit buttons. Apart from that I figure it has an entirely different feel. ToggleSwitches are designed to imitate physical switches, which I'm assuming is why the strict on/off usage guidelines make sense.

2018-12-06 14:48 UTC, hodoea commented
Yes ofc, I was just a little bit confused because of the second statement in the guidelines: typisk i formen "ja eller nei", **eller "av eller på"*.

2018-12-06 15:01 UTC, hodoea commented
Yes ofc, I was just a little bit confused because of the second statement in the guidelines: typisk i formen "ja eller nei", **eller "av eller på"*.

2018-12-06 21:02 UTC, hodoea commented
Nvm, Adi shared this on the background for it: 

_Radio switch var laget til å tydeligjøre lett valg på mobil. Det var laget for ca. 4 år siden som en del av NN (nye nettsider) og DNA (Forsikring) prosjekter akkurat i starten av å jobbe med den nye profil refresh. Det var testet i bilforsikring kjøpsløp på mobil og fungerte skikkelig bra pga at det var veldig tydelig valg og veldig oversiktlig, plus at det var veldig mobilvennlig. Det var mange runder ift utforming av knappen og det som ble til slutt var en blanding av en som eksisterte før og ny stilen. Jeg synes det er ikke den fineste komponent i at det er for tungt i mørk blå men det kunne vi justere. Ideen er å bare bruke det til lett valg, som “Ja/Nei”. Så snart som det er mer en 3 valg bør man bruke vanlig radio knapper (i en list nedover). Det har alltid vært et spørsmål om hvis vi trenger å ha en så stor og tydelig variant ift helhetlig visuell hierarkiet (f.eks i dag konkurrere den mørke blå med alle andre action knapper på sidene) så det kunne man godt se på. Grunnen at det er mørkt blå er at ideen var at alle “valgt” states burde være likt på tvers av designet og akkurat da brukte vi mørk blå mye mer i designet vårt. I dagens design er det litt for tungt i sammenheng med alle andre knapper osv og kunne være f.eks en mer subtil lys blå, eller bare bruke vanlig radio knapper men passe på at de har en stor klikkflate._

2018-12-07 07:59 UTC, selbekk commented
Perhaps the difference can be explained like this?

The toggle switch is for "on / off" choices, typically found in settings, while the radio switch is for `yes / no" choices, typically found in forms with a submit button?

2018-12-07 11:54 UTC, hodoea commented
Takk. Har allerede skrevet i første avsnitt at man ikke skal bruke toggle-switch dersom man har bruk for en send/lagre knapp i tillegg. Men jeg la det til igjen i forslaget ditt uansett. @selbekk  


<img width="518" alt="skjermbilde 2018-12-07 kl 12 52 06" src="https://user-images.githubusercontent.com/8971560/49646358-16e77d80-fa1f-11e8-8f6c-00ba2680a530.png">

2018-12-07 12:10 UTC, selbekk commented
som jeg skulle gjort det selv @hodoea :laughing: tusen takk!

2019-05-15 05:28 UTC, ivarni commented
@antidecaf Are this one pretty much ready to go once the documentation is added?

2019-05-15 08:07 UTC, antidecaf commented
@ivarni Yeah, pretty much. But it doesn't have a green light from UX at the moment, it's still being tested in one app afaik. Not sure if it will be merged or not in the end, but for now we can leave it.

2020-02-12 11:17 UTC, closed without merging