fix(ffe-account-selector-react): Optimize performance of suggestion list
SpareBank1/designsystem pull request #568
Opened 2019-02-09 20:40 UTC by simjes

Not sure if you still want this, but fixes #367. It might be better to rewrite for #501 first?

The list will require a height, as `react-window` does not automatically shrink if needed bvaughn/react-window#121.

Doesn't look great when items doesn't max out the height.
![image](https://user-images.githubusercontent.com/6494049/52526010-c4427000-2cb2-11e9-8d03-e56a2e65672f.png)

2019-02-10 08:38 UTC, simjes commented
I could implement an AutoSizer if you want me to continue on this PR, f.ex: https://github.com/souporserious/react-measure

2019-03-15 08:39 UTC, henrikhermansen commented
This seems to me like a good start. I see the need for improved performance here, and react-window is a good option for that. I do, however, feel that this will only be a good solution if you can implement auto sizing, as it doesn't look nice for just a few accounts (as your screen shot illustrates).

Great if you can keep up the work on this, and I'll review it again when you have implemented auto sizing :)

2019-03-15 08:40 UTC, henrikhermansen requested changes
This seems to me like a good start. I see the need for improved performance here, and react-window is a good option for that. I do, however, feel that this will only be a good solution if you can implement auto sizing, as it doesn't look nice for just a few accounts (as your screen shot illustrates).

Great if you can keep up the work on this, and I'll review it again when you have implemented auto sizing :)

2019-04-23 20:45 UTC, simjes commented
Abandoning this as it is not up to standards, will work on a new PR instead

2019-04-23 20:45 UTC, closed without merging

2020-04-21 17:42 UTC, ksawerysb1 commented
@simjes @henrikhermansen har vi noe nytt på denne fronten? Eller en ny komponent som kan søke og scrolle 1000+ resultater?

2020-04-22 07:14 UTC, ksawerysb1 commented
Liten oppdatering, jobbet litt med å få denne saken rebased på nyeste release, også fikset en del rundt visning og markup:
https://github.com/ksawerysb1/designsystem/commit/a2d1ac1bab266e662db0f598c379d7ab67c6c986