feat(ffe-searchable-dropdown-react): fix me
SpareBank1/designsystem pull request #754
Opened 2019-11-01 13:40 UTC by pethel

2019-11-04 13:00 UTC, ivarni commented
I'm in favour, but never used the `ffe-searchable-dropdown` module and can't really have an opinion on the actual changes. Do we know if any teams are currently using it and who they are?

2019-11-04 13:14 UTC, pethel commented
@ivarni Me and @henrikhermansen use it in team sparing. If you know of some other team using it, please feel fre to add them to this pull request.

A search gave me this:
* NPA bm-master
* adobe-experience-manager sb1-nettsider-skjema
* Digitalt Rådgiverløft Forsikring skr-app
* NPA bm-autorisasjon
* api.sparebank1.no apigw-bm-autorisasjon
* Pensjon BM Kundeklient Forsikring BM
* KFP kfp-motor

2019-11-05 14:42 UTC, hdaljord requested changes

2019-11-05 14:42 UTC, hdaljord commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.md
> +    <SearchableDropdown
Kan du ta med ett eksempel der det sendes inn en inputverdi? (dette var med i de gamle eksemplene)

2019-11-05 15:57 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.md
> +    <SearchableDropdown
Der er ikke lenger noen behov for og sende med en inputverdi. Det er en state som hanteras internt av downshift. Nå sender man bare med en initialValue(hvis man vill) og lysnar på onChange når brukaren gjort ett valg. Enig?

Eller mente du kanskje bare att jag viser bruk av defaultverdi?

Sjekk gjerne ut branchen og prøva litt.

2019-11-06 06:58 UTC, hdaljord commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.md
> +    <SearchableDropdown
Ja, det var akkurat det jeg lurte på, bare et eksempel der bruken av defaultverdi kommer fram, så man slipper å lete :)

2019-11-06 09:10 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.md
> +    <SearchableDropdown
https://github.com/SpareBank1/designsystem/pull/754/commits/899a1465cc56f7d0df60683d7ccb65a6ecf6171e

2019-11-06 10:45 UTC, hdaljord submitted a review, later dismissed

2019-11-06 11:26 UTC, kwltrs commented
Approved om den virkelig løser #500. Noen som kan bekrefte det?

2019-11-06 11:34 UTC, pethel commented
fra https://github.com/SpareBank1/designsystem/issues/500
`First quick test of examples 01-04 shows it also have some issues, but generally it works better than ours and it would be a good thing contributing to it.`

Kan vi kanske få @42tte og prova litt nå. Issuen er ju ca et år gammal og har vell sikkert skett en del med downshift.

2019-11-08 16:41 UTC, pethel commented
@kwltrs 
Hvis ingen annen har mulighet så har jag provat lite med  Chrome Vox  selv. Jag mener det er ett betydligt lyft mot det vi har idag som jag også provade i Chrome Vox nå. Hade hopet noen annen også hade mulighet att testa lite.

Vid fokus:
ChromeVOX siger att det er en autocomplete list med x alternativer. Bruk pilar for og navigera og enter for og gjøre ett valg.

Når man navigerar med pilarna:
Han siger "Bedriften 123434434" selected 1 of x når når man navigerar med pilarna

Når ingen søke treff:
Ger besked om att det ikke er noen treff. 
Problem hvis man bruker hvis ekstra resultater når det ikke er noen treff? Da får man ikke besked utan får besked om att det finnes 3 alternativer.

Når man velger noe:
Alternativet leses op(2 ganger).

Når man sletter noe.
(aria-)labeln på slettknappen leses op når den får fokus.

2019-11-12 08:54 UTC, 42tte commented
Tested with VoiceOver (Mac) and Safari + Chrome. Work as expected. Someone might want to test on Windows with Narrator or NVDA and Android with Talkback.

Bear in mind that content also need to be accessible. Ie: "Bedriften 912602370 5 ulest" could need some explaining "Bedriften, kontonummer 912602370, 5 ulest meldinger"

2019-11-12 08:55 UTC, 42tte approved these changes

2019-11-12 10:02 UTC, henrikhermansen approved these changes
Code changes looks good to me.
I haven't had the chance to test it with screen reader, but I trust the judgement of @pethel and @42tte that this is a huge improvement.

2019-11-12 11:40 UTC, merged