feat(ffe-searchable-dropdown-react): open on focus
SpareBank1/designsystem pull request #849
Opened 2020-02-10 19:04 UTC by pethel

I have created this pr to see if you like the behaviour better. If you like it I will write tests for it or fix existing ones.

2020-02-11 20:04 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/index.d.ts
> +    dropdownAttributes: string[];
`dropdownAttributes` and `searchAttributes` must be existing keys in `DropDownItem`. Can I achive this with typescript?

2020-02-11 20:04 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/index.d.ts
> +    inputProps?: React.InputHTMLAttributes<HTMLInputElement>;
This means the props are limited to attributes allowed on an html input tag?

2020-02-11 20:06 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                    : String(!!ariaInvalid)
avoid `aria-invalid="undefined"`

2020-02-13 12:15 UTC, tutturen requested changes

2020-02-13 12:15 UTC, tutturen commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Hva med å droppe isOpen-sjekken og heller bruke `openMenu()`?

2020-02-13 12:15 UTC, tutturen commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Hva med å droppe isOpen-sjekken og heller bruke `closeMenu()`?

2020-02-13 12:15 UTC, tutturen commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Hva med å droppe isOpen-sjekken og heller bruke `openMenu()`?

2020-02-13 12:15 UTC, tutturen commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                    !!trimmedInput.length && trimmedInput !== selectedItem;
```suggestion
                    trimmedInput.length > 0 && trimmedInput !== selectedItem;
```

2020-02-13 18:58 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Ja ern enig. Hadde ikke fått med meg att den fann en closeMenu  og openMenu

2020-02-13 19:05 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Ja enig, burde sett det
59c92b134df6513fca2bd0906001742f7445281a

2020-02-13 19:05 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Ja enig, burde sett det
59c92b134df6513fca2bd0906001742f7445281a

2020-02-13 19:06 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                                        toggleMenu();
Ja enig burde sett det
59c92b134df6513fca2bd0906001742f7445281a

2020-02-13 19:07 UTC, pethel commented on packages/ffe-searchable-dropdown-react/src/SearchableDropdown.js
> +                    !!trimmedInput.length && trimmedInput !== selectedItem;
Her er det samma før meg. Du får endringerna hvis du ønsker.

2020-02-28 11:20 UTC, hdaljord approved these changes
I haven't gone through the code, but the solution works as expected :+1:

2020-02-28 12:33 UTC, henrikhermansen approved these changes

2020-02-28 12:46 UTC, pethel commented
@tutturen har fikset de du påpekte. kan du approva så vi får merge? Ær blockert for nå

2020-02-28 13:10 UTC, tutturen approved these changes
Har ikke verifisert TS-typene, men ser ok ut på overflaten.

2020-02-28 15:46 UTC, merged