Issue/367 high capacity component
SpareBank1/designsystem pull request #886
Opened 2020-04-22 16:08 UTC by ksawerysb1

using react-window

Based on: #568

Uses a highCapacity prop to determine suggestion rendering. By default uses the "old" rendering.
highCapacity=true for react-window based.
Rebased and fixed sizing and markup issues, uses "ul" and "li" instead of divs, tests are running fine again. Bumped react-window to latest version.

2020-04-27 11:11 UTC, kwltrs requested changes
Jeg liker testene!
Kan du squashe de to commitene og endre det fra `fix` til `feat`?

2020-04-27 11:11 UTC, kwltrs commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.js
> +    highCapacity: bool,
Kan du legge til en kommentar som dokumenterer denne prop? Synes navnet er ikke helt selvforklarende.

2020-04-27 11:11 UTC, kwltrs commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.spec.js
> +configure({ adapter: new Adapter() });
Denne koden er allrede med i `/test-setup.js`, så det blir redundant her.

2020-04-27 11:11 UTC, kwltrs commented on packages/ffe-account-selector-react/src/subcomponents/suggestion-high-capacity/SuggestionListContainer.js
> +/* TODO: Needs an aria-role, but I'm not sure which is correct */
Denne kommentar kommen å bli glemt og aldri fikset. Enten fikse nå eller åpne en issue.

2020-04-27 12:45 UTC, ksawerysb1 commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.spec.js
> +configure({ adapter: new Adapter() });
Hadde problem med lokal test for en eller annen grund, "fungerer det hos dere" uten?

2020-04-27 12:51 UTC, ksawerysb1 commented on packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.spec.js
> +configure({ adapter: new Adapter() });
Hvis jeg kjører `npm run test` i root folderen så får jeg:
  ● <BaseSelector> highCapacity › should display high capacity component when highCapacity=true


          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
          To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see https://airbnb.io/enzyme/docs/installation/index.html

      35 | 
      36 | function mountBaseSelector(props) {
    > 37 |     return mount(<BaseSelector {...propsBaseSelector()} {...props} />);
         |            ^
      38 | }
      39 | 
      40 | function assertHomeEnd(keyCode, stubMethodName) {

2020-04-27 13:14 UTC, steffenz commented
Jeg kjenner ikke denne komponenten så godt at jeg greier å se eventuelle ringvirkninger. Jeg har imidlertid hatt litt problemer med denne komponenten før, og vil egentlig ha den bort. Jeg skal forsøke å forklare hvorfor: 

Den er for spesialisert til at den er særlig nyttig til andre ting. Slik jeg ser det burde vi heller fokusert på å lage en robust "Select" komponent, med støtte for filtrering, flervalg osv. Først når denne er robust kan vi eventuelt vurdere å lage en AccountSelector basert på Select komponenten. Idag finnes det flere komponenter som nesten gjør det samme.

Jeg fikk spesielt sett hvor stygt dette er i organisasjonssøket som finnes rundt forbi. Den lar deg søke etter organisasjonsnavn eller nummer, men mapper alt om til "kontoer" for å slippe å skrive et filtrerbart søk på nytt. Jeg laga en gjenbrukbar komponent for dette selv som også baserte seg på denne måten, men det føltes veldig feil.

Dette er ikke kritikk mot koden mot forslaget ditt som isolert sett er bra. Jeg barer lurer på om vi skal løfte blikket litt her før vi bruker for mye tid på noe vi på et senere tidspunkt skal putte ei kule i.

Hva tenker dere andre om dette?

2020-04-27 13:24 UTC, ksawerysb1 commented
@steffenz tror det er veldig greit å ha en komponent som gjør det denne gjør straight out of the box.
Men også jeg tror vi kan legge til samme type endring/prop i select komponenten, i BM trenger vi optimalisering for store datamengder særlig hvis vi skal støtte gamle maskiner og IE.

2020-04-27 13:28 UTC, ivarni commented
Jeg tenker at hvis det allerede er lagt ned arbeid her som fikser et reellt problem så er det ikke noe i veien med merge det inn selvom komponenten kanskje skal fjernes.

Skal man se på noe generisk søke-dropdown aktig er det sikkert bedre å plukke opp tråden på 
https://github.com/SpareBank1/designsystem/tree/develop/packages/ffe-searchable-dropdown-react enn å lage no helt nytt.

Vi droppet begge deler til fordel for [downshift](https://www.npmjs.com/package/downshift) for en stund siden.

2020-04-28 09:15 UTC, steffenz commented
@ksawerysb1 Jeg er helt enig, det kan absolutt bli med i den rene "select" komponenten også. Den bør absolutt være så optimalisert som mulig uansett. Hvor lange lister snakker vi om egentlig? Den bør takle ganske store lister, men på et tidspunkt er det kanskje hensiktsmessig å ha paginering/filtrering fra backend? Sånn type når lista er tusenvis av elementer lang? 

@ivarni Jeg var faktisk ikke klar over downshift, men prøvde på et tidspunkt å lage en egen variant. Det tror jeg ikke nødvendigvis er så lurt, men gav meg en del nyttig erfaring. 

Jeg vet ikke helt hva jeg skal si med tanke på å merge inn endringene. Hvis dette er en døende komponent er det kanskje ikke vits, men på en annen side; om vi ikke risikerer å breake noe med denne endringer kan vi jo ta den inn. Hva tenker du selv, @ksawerysb1 ?

Igjen, jeg har ikke så mye erfaring med komponenten at jeg greier å se at noe skal gå galt her. Hva tror dere @antidecaf og @kwltrs ? Og bør vi ha noen betenkeligheter med å eventuelt depende på "downshift" (som vi allerede åpenbart gjør i searchable-dropdown komponenten). Kan jo se ut som den gir oss en del usability ting gratis (som vi jo vet ikke er optimalt på account-selectoren).

2020-04-28 10:20 UTC, ksawerysb1 commented
@steffenz vi har lyst å beholde muligheten å bare bla gjennom for alle, fleste har par stykker men maksimum er tusenvis. Jeg har testet komponenten med flere tusen og den fungerer fint.
Optimaliseringer hver enkelt sted hvor du velger konto blir vanskelig å vedlikeholde og tenger at det er greit å ha det i FFE.
Vi har lyst å merge den inn å bruke denne uken hvis det er mulig.
Hvis denne komponenten skal ikke få support lenger så kan man understreke det i dokumentasjonen.

2020-04-28 10:27 UTC, ksawerysb1 commented
FFE searchable dropdown bruker jo downshift men den løser ikker vår problem, den feiler også hvis det er for mange objekter i dropdown:
https://github.com/SpareBank1/designsystem/search?q=downshift&unscoped_q=downshift

2020-04-28 13:28 UTC, steffenz commented
Skjønner. Hva vil det si at det feiler? Går ting ekstremt treigt, eller feiler hele greia? Hvordan er utsiktene for å eventuelt reparere patche det i denne komponenten, for så å bruke den i kontovelgeren? Angående merging så skal jeg ta en prat med teamet og høre hva vi bør gjøre her.

2020-04-28 14:01 UTC, ksawerysb1 commented
@steffenz vi kan se på samme type suggestion rendering i searchable dropdown, men kanskje neste uken, denne uken må jeg ha en løsning for BM.

2020-04-28 14:17 UTC, steffenz commented
Det hadde vært helt supert! Skjønner at du må ha på plass løsningen, men er det ikke mulig å eventuelt bare bruke en lokal kopi i mellomtiden? Vil unødig forhaste noe inn hvis vi må endre på det etterpå uansett. Ikke meningen å være vanskelig her, og på sikt vil vi senke terskelen for at folk skal kunne bidra (forhåpentligvis med mindre komponenter som er mer oversiktelige). Jeg er uansett i gang å ta en prat med de andre i teamet og høre hva vi bør gjøre her - vil ikke ta avgjørelsen om å merge inn alene :)

2020-04-29 07:49 UTC, ksawerysb1 commented
@steffenz jeg har laget 2 PR, en som endret på suggestions for alle og denne her som har en optional prop. Det var tanken med å hjemme det slik at det påvirker ikke andre. 
Bankene venter på en release og vi trenger denne PR ;) 
Tror ikke det er særlig ryddig for oss å ha en bootleg FFE for BM.

2020-04-29 12:52 UTC, kwltrs approved these changes

2020-04-29 13:28 UTC, merged