fix(ffe-form-react): remove checkbox props
SpareBank1/designsystem pull request #914
Opened 2020-07-30 06:26 UTC by ivarni

BREAKING CHANGE:

Instead of having an `innerRef` prop, use the more modern
approach with `React.forwardRef`. This means that instead
of using the `innerRef` prop, refs should be passed as
they would to any other React element.

```diff
- <Checkbox innerRef={ref} />
+ <Checkbox ref={ref} />
```

While we're doing breaking changes anyway, removed
support from the two deprecated props `label` and
`valid`. Use children and `aria-invalid` instead.

```diff
- <Checkbox invalid={true} label="To arr is pirate" />
+ <Checkbox aria-invalid={true}>To arr is pirate</Checkbox>
```

2020-07-30 08:51 UTC, steffenz requested changes
Thanks for your contribution :tada: 
However, it seems like your changes broke some of the tests (according to the Travis logs). If you could adjust them to fit your changes, that would be much appreciated :smile:

2020-07-30 08:55 UTC, ivarni commented
Sure, I'll take a look. I thought I ran them locally but it's possible I forgot 🦡

2020-07-30 09:52 UTC, ivarni commented
Oh, clearly I didn't run them 😂

2020-07-30 10:40 UTC, kwltrs approved these changes

2020-07-31 08:33 UTC, steffenz approved these changes

2020-07-31 09:26 UTC, merged