feat(ffe-cards-react): forward ref
SpareBank1/designsystem pull request #923
Opened 2020-08-10 05:45 UTC by pethel

Forwardref 
## Beskrivelse

## Motivasjon og kontekst

Jag har behovet for en ref på kortet i en slider for og kunne sjekke klasser på omgivande elementer. 

## Testing

2020-08-10 11:49 UTC, kwltrs requested changes
Dette bør være en breaking change. Se https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

2020-08-12 08:44 UTC, henrikhermansen submitted a review, later dismissed

2020-08-12 09:43 UTC, henrikhermansen approved these changes

2020-08-12 11:14 UTC, kwltrs approved these changes

2020-08-12 11:21 UTC, merged