feat(ffe-message-box-react): add role="alert" to ErrorMessage
SpareBank1/designsystem pull request #944
Opened 2020-09-28 09:53 UTC by torkjels

## Beskrivelse

Bruker samme fremgangsmåte som i eksempel #2 på MDN sin side [Using the alert role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Example_2_Dynamically_adding_an_element_with_the_alert_role)

## Motivasjon og kontekst

Dette gjør at skjermleserbrukere ser skjemafeilmeldinger med én gang de oppstår, på samme måte som en "seende" bruker ser de med én gang.

## Testing

Fyrte opp designsystemet på lokal maskin og testet med Talkback på Android og Orca på Firefox.

2020-09-28 10:36 UTC, antidecaf approved these changes

2020-09-28 11:29 UTC, pethel commented
Jag tror det trengs en timeout innan meldningen vises for att dette skall funka fint på olika skærmlæsare. 

fra https://dequeuniversity.com/ dette er ju aria-live men role alert har vel en aria-live i seg skjønner jag det riktig.

![image](https://user-images.githubusercontent.com/2248579/94426877-8697a100-018e-11eb-8310-4afa20a428de.png)

2020-09-28 11:31 UTC, pethel requested changes
Se kommentar anngående timeout

2020-09-28 11:34 UTC, pethel commented
Legger med den og
![image](https://user-images.githubusercontent.com/2248579/94427396-4d136580-018f-11eb-9f26-bc09ca70036d.png)

2020-09-28 12:39 UTC, kwltrs commented
@pethel Jeg henger ikke helt med hva du ønsker endret. Noen typ førstegangs-rendering med tom inner-text og en automatisk re-rendering med tekst?

2020-09-28 12:59 UTC, pethel commented
> @pethel Jeg henger ikke helt med hva du ønsker endret. Noen typ førstegangs-rendering med tom inner-text og en automatisk re-rendering med tekst?

@kwltrs 
Nu har jag ju kun lest dette på den kursen jag linker til men jag ser før meg man bør gjøra noe slikt:

```
import React, { useState, useEffect } from 'react';

interface Props {
    message: string;
}

const ErrorMessage: React.FC<Props> = ({ message }) => {

    const [messageWithTimeout,setMessageWithTimeout] = useState(message);

    useEffect(() => {
        setMessageWithTimeout('');
        setTimeout(() => setMessageWithTimeout(message), 2000);
    }, [message]);

    return (
        <div role="alert" >
            { messageWithTimeout }
        </div>
    );
};

export default ErrorMessage;
```

Slik tolkar jag det iaf :)

2020-09-28 13:17 UTC, pethel commented
Jag husker sikker feil men tror det var VoiceOver som var lite spesiell her?

2020-09-28 13:23 UTC, pethel commented
@torkjels  sorry.. ikke meningen og closa.. skulel fjerne en kommentar. Beklager :)

2020-09-28 14:13 UTC, pethel commented
Ønsker legge til att måte dette er testet nok ikke er representativt for hvordan dom blir brukt? 
I denne testen så var dom der hele tiden. Fra initial render. Jag vet ikke men andra apper men vi bruker veldigt ofte disse for og legge til en meldning efter att ci gjorde noe asynchront.

2020-09-30 08:18 UTC, henninghuseby-sb1 commented
Litt usikker på om `role="alert"` er veien å gå for disse meldingene? Er det slik at vi da alltid ønsker at de blir lest opp av skjermleseren med en gang siden også lastes? At feilmeldingen blir lest opp når komponenten blir lastet etter input fra brukeren synes jeg er bra men at den alltid skal være `role="alert"` er jeg heller usikker på.

2020-09-30 08:25 UTC, henninghuseby-sb1 commented
@pethel jeg har testet litt på skjermlesern til mac og den leser opp alt som blir merket med `role="alert"` så fort komponenten lastes. Noe også [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Example_2_Dynamically_adding_an_element_with_the_alert_role) sier vil fungere. Men som sagt har jeg kun testet med native mac skjermleser

2020-09-30 08:46 UTC, pethel commented
> @pethel jeg har testet litt på skjermlesern til mac og den leser opp alt som blir merket med `role="alert"` så fort komponenten lastes. Noe også [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Example_2_Dynamically_adding_an_element_with_the_alert_role) sier vil fungere. Men som sagt har jeg kun testet med native mac skjermleser

Super. Jag vill ikke vare vannsklig alltså men har vi prøvd og feks submitta en form og sedan visa en meldning? Alltså att elementet ikke er tillstede vid sidlast. Jag har ikke noen praktisk erfaring her alltså, prover bare formiddla vad jag fått med meg når jag lest på om dette :)

2020-09-30 09:09 UTC, pethel commented
> Litt usikker på om `role="alert"` er veien å gå for disse meldingene? Er det slik at vi da alltid ønsker at de blir lest opp av skjermleseren med en gang siden også lastes? At feilmeldingen blir lest opp når komponenten blir lastet etter input fra brukeren synes jeg er bra men at den alltid skal være `role="alert"` er jeg heller usikker på.
> 
> Tenker da heller at det er viktig at utropstegnet får en forklaring for de som bruker skjermleser, for slik den er i dag så er det fort meldingen ikke oppfattes som en error melding for de med skjermleser

Jag lurer på i vilka tilfeller denne meldninen er tilstede i en sidlast allrede? Hmm 
Anngående sista punkten din så ær vell problemet att skjermleserna ikke får med seg att det dyket op en meldning. Hvis jag ikke husker feil så var dette  feedback fra en faktiskt kunde/bruker som kom og presenterte noen fund han gjort på betalning.

2020-09-30 09:29 UTC, torkjels commented
Veldig bra diskusjon her, altså! :+1:
Jeg er forsåvidt enig i at mye dokumentasjon sier at `aria-live` må være tilstede på sidelast for at det skal funke. Og at `role="alert"` har en implisitt `aria-live`. Men jeg forstår det også som at `role="alert"` ikke er **ekvivalent** med `aria-live`, så det er ikke gitt at akkurat de samme tingene gjelder for begge.. men det kan hende det er mest ønsketenking :smile: 

Tanken min var at siden det er et [eksempel på MDN som gjør det samme](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Example_2_Dynamically_adding_an_element_with_the_alert_role)  og vi har testet med innebygd skjermleser på både Android og Mac og det funker bra så skal det være good.
Men som du påpeker betyr jo ikke det nødvendigvis at det er "riktig" måte å gjøre det på.
Jeg har hvertfall testet å legge til `role="alert"` dynamisk på PRet om `ErrorFieldMessage` https://github.com/SpareBank1/designsystem/pull/943. Da testet jeg ved å fyre opp designsystemet på localhost:6060, fant fram `InputGroup` og togglet feilmeldingene vha. "Skru feilmeldinger av/på"-knappen. Det funket fint.

Jeg tror det finnes tilfeller hvor en slik melding skal vises ved sidelast. For eksempel hvis man vet at noen systemer er nede/treige og vil advare brukeren (kanskje et info-element gir mer mening akkurat da, men konseptet er det samme), eller hvis man skal si at "Hei, lånet ditt har blitt avvist!" eller noe sånt når man går inn på en side. Eller feks hvis en brukerhandling (feks submit av et form) tar deg til en ny side hvor resultatet av submit'en vises (litt old school, men kan skje), da vil man kanskje presentere en slik feilmelding der på sidelast. Det er ikke helt utenkelig at det kan skje, og da er det også veldig viktig for skjermleserbrukere å få det med seg.
Slike meldingsbokser skal jo bare brukes (etter hva jeg forstår) når det er noe feil som har skjedd som brukeren må få med seg. Hvis man er en seende bruker får man det absolutt med seg, disse boksene er umulig å unngå. Men som en skjermleserbruker forsvinner de lett.

**tldr:**
Å legge på en `role="alert"` er en _utrolig_ enkel fiks. Den deler mange egenskaper med `aria-live`, og hvis vi skal si at `aria-live` sin dokumentasjon også gjelder 100% for `role="alert"` så er ikke denne løsningen helt god ifølge boka. Men det funker på alt vi har testet på, så jeg mener vi kan tillate oss å si at det er innafor.

2020-09-30 09:46 UTC, pethel approved these changes

2020-10-02 08:28 UTC, merged

2020-10-05 09:15 UTC, hdaljord commented
Uten at elementet finnes i dom-en vil det ikke fungere så bra i alle nettlesere. Testet nylig å bruke aria-live og oppdatering med IE (eller chrome, jeg husker ikke helt) på windows og elementet ble ikke lest opp før jeg inkluderte et placeholderelement. Dvs. hvis role alert oppfører seg som aria-live region fungerer det ikke. Kravet til nettleser burde vel gjelde for bruk sammen med skjermleser også? Det bør i hvert fall verifiseres at denne løsningen fungerer for vanlige nettlesere på windows også, ikke bare android og mac.