fix in multiple packages:  Change font size and line height to rem
SpareBank1/designsystem pull request #969
Opened 2020-11-18 10:15 UTC by HeleneKassandra

## Beskrivelse
Denne fiksen setter en default font-size på html elementet, og endrer alle andre font-size og line-height verdier i designsystemet til rem. Det skal ikke være noen visuelle endringer. 

## Motivasjon og kontekst
Noen brukere hadde problemer med å forstørre teksten på iOS.
Vi ønsker at brukere skal selv kunne forstørre innholdet så mye de selv ønsker.

## Testing
Kjørte npm start, og sammenlignet localhost versjonen (med endringene) med live versjonen design.sparebank1.no
Så ingen visuelle endringer på komponentene.

2020-11-18 10:49 UTC, antidecaf submitted a review, later dismissed

2020-11-18 10:57 UTC, kwltrs requested changes
Du må ha med `BREAKING CHANGE` i commitene slik at det blir en ny major-release på det pakkene. [Se eksemplet her på wiki'n](https://github.com/SpareBank1/designsystem/wiki/Bidra:-Fra-issue-til-pull-request#commit-meldinger).

2020-11-18 10:57 UTC, kwltrs commented on packages/ffe-core/less/font-sizes.less
> +}
Denne regeln burde ikke være her fordi `font-sizes.less` er liksom en bibliotekfil som inneholder kun [less-mixins](http://lesscss.org/features/#mixins-feature), dvs. om man importerer denne filen i en annen less-fil så får man ingen css-regler men kan bruke de mixins `.ffe-fontsize-*()` i sin kode.
Derfor er det bedre å ha den font-size- regelen i `ffe-normalize.less`.

2020-11-18 11:40 UTC, HeleneKassandra commented on packages/ffe-core/less/font-sizes.less
> +}
Jeg har ikke noe ffe-normalize.less fil?  Jeg ser den er importert, men jeg finner ikke selve filen?  Jeg finner normalize.css, men det er jo tredjepart

2020-11-18 11:50 UTC, antidecaf commented on packages/ffe-core/less/font-sizes.less
> +}
Den ligger i ffe-core, her: `designsystem/packages/ffe-core/less/ffe-normalize.less`

2020-11-18 11:53 UTC, HeleneKassandra commented
> Du må ha med `BREAKING CHANGE` i commitene slik at det blir en ny major-release på det pakkene. [Se eksemplet her på wiki'n](https://github.com/SpareBank1/designsystem/wiki/Bidra:-Fra-issue-til-pull-request#commit-meldinger).

Breaking change i commit tittelen eller funker det i content?

2020-11-18 11:59 UTC, kwltrs commented
> Breaking change i commit tittelen eller funker det i content?

I content.

> Og hvordan kan jeg legge til det nå i etterkant?

Jeg bruker `git rebase --interactive develop` på cli for å reworde commits. Finnes helt sikkert noe med bedre UI, men jeg likker jo terminalen ;-)

2020-11-18 12:03 UTC, kwltrs commented on packages/ffe-core/less/font-sizes.less
> +}
Har du https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core/less/ffe-normalize.less ?

2020-11-18 12:06 UTC, HeleneKassandra commented
> > Breaking change i commit tittelen eller funker det i content?
> 
> I content.
> 
> > Og hvordan kan jeg legge til det nå i etterkant?
> 
> Jeg bruker `git rebase --interactive develop` på cli for å reworde commits. Finnes helt sikkert noe med bedre UI, men jeg likker jo terminalen ;-)

Skal jeg ta det mot develop branchen?  Eller den branchen jeg lagde for dettte?  Jeg har dårlig erfaring med rebase

2020-11-18 12:07 UTC, HeleneKassandra commented on packages/ffe-core/less/font-sizes.less
> +}
Fant den,  jeg må ha vært blind. fikset nå

2020-11-18 12:13 UTC, kwltrs commented
> Skal jeg ta det mot develop branchen? Eller den branchen jeg lagde for dettte?

På din branch. Istedenfor `develop` i kommandot `git rebase --interactive develop` kan du bruke hashen til commiten i develop din branch tok utgangspunkt i. 

> Jeg har dårlig erfaring med rebase

Det har vi alle. Men også mange bra minnen ;-)

2020-11-18 13:00 UTC, fredrikp commented
Jeg lastet ned CSS-filen som @HeleneKassandra la ut i Slack-kanalen. Så laget jeg en html-fil med noen av overskriftene. Testet i Safari på to iPhoner, en med standard skriftstørrelse og en med XXXL skriftstørrelse. Teksten ble seende likt ut på begge telefonene, så det ser ikke ut til at denne PRen muliggjør støtte for Dynamic Type på iOS. 

Se denne artikkelen for en kjapp intro til hvordan Dynamic Type fungerer:
https://useyourloaf.com/blog/using-dynamic-type-with-web-views/

Her er Apples oversikt over predefinerte skriftstørrelser, se avsnitt "Dynamic Type Sizes":
https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/

![Native oversikt](https://user-images.githubusercontent.com/888442/99533431-2fe85f80-29a6-11eb-9f54-98f9ad66cc6c.png)

2020-11-18 13:06 UTC, fredrikp commented
Et eksempel på hvordan Dynamic Type kan kombineres med en custom font (eksemplet er for en statisk webside+css bakt inn i en iOS-app):
```
@font-face {
    font-family: 'MuseoSans-500';
    src: local('MuseoSans-500'),url('MuseoSans_500.otf') format('opentype');
}

body {
    margin: 16pt;
    font: -apple-system-body;
    font-family: "MuseoSans-500";
}

h1 {
    font: -apple-system-title1;
}
```
Nå vil body og h1 vises med Museo Sans 500, men størrelsen vil være 17pt og 28pt for en bruker med standard skriftsstørrelse, og de vil skalere for andre skriftsstørrelser.

2020-11-18 13:12 UTC, ivarni commented
Dette kan fikses mye lettere med `commit` kommandoen, bare å kjøre `git commit --amend`. Rebase er overkill :)

2020-11-18 16:23 UTC, sondrelarsen commented
Denne PR-en vil legge til rette for at vi kan spesifisere relative fontstørrelser sjølv i kombinasjon med Dynamic Type. For å faktisk "koble seg på" Dynamic Type så kan man legge på følgende i appen som konsumerer komponenter fra designsystemet:

```css
@supports (font: -apple-system-body) {
  :root {
    font: -apple-system-body;
  }
}
```
(Merk: dette legges på `:root`, siden base font-size må ligge på en "child" av elementet som bruker `-apple-system-*` regelen).

Har verifisert dette ved å laste ned/ta i bruk CSS-fila med endringane, samt legge til regelen over.

Et mulig alternativ er å legge regelen over inn i designsystemet, men det er kanskje greiest å la det vere en "opt-in" å faktisk benytte seg av Dynamic Type?

2020-11-19 08:13 UTC, fredrikp commented
@sondrelarsen Jeg la inn snutten med "supports" i tillegg, og da fungerer Dynamic Type i native app med Webview også. Veldig bra!

![Native oversikt](https://user-images.githubusercontent.com/888442/99639023-64602800-2a47-11eb-8334-49e05c6a7861.png)

2020-11-19 10:16 UTC, antidecaf commented
> **Et mulig alternativ for å slippe å måtte gjere dette manuelt i kvar enkelt app, er å legge regelen over inn i designsystemet, dog det er kanskje greiest å la dette vere en "opt-in" (dvs. å faktisk benytte seg av Dynamic Type blir opp til kvar einskild app å bestemme)?**

Høres fornuftig ut. Kanskje legge det i en egen `dynamic-type.less` som er optional?

2020-11-19 11:53 UTC, kwltrs approved these changes

2020-11-20 12:30 UTC, merged