fix(ffe-context-message-react): replace header tag
SpareBank1/designsystem pull request #970
Opened 2020-11-18 13:23 UTC by HeleneKassandra

## Beskrivelse
Denne fiksen legger til en ny prop som heter headerHTMLElement, som lar deg bestemme hvilket html-element 
tittelen i context-message skal være.  Hvis ingenting er satt, vil den generere en div. Klassen og id er som før, så det skal ikke være noen visuelle endringer. 
 
Tidligere ble det alltid generert en <header> tag, men dette er ikke semantisk riktig i denne konteksten. Siden denne komponenten kan brukes ulike steder i hierarkiet, så ga det ikke mening å hardkode ett heading nivå, da dette også fort kunne bli feil. 

## Motivasjon og kontekst
Riktig HTML-syntaks og struktur er viktig for Universell Utforming, da det kan påvirke hvilken rekkefølge skjermlesere leser innholdet. Det er ikke semantisk riktig å bruke headere, inne i en div på måten det har blitt hittil. 

## Testing
Kjørt npm start og sjekket endringen opp mot localhost, ved å inspekte koden etter å ha gjort endringer i "kode demoen" 
(view code, delen der man kan endre kode). La til den nye propertyen, og testet at html elementet endret seg og defaultet til div.

2020-11-19 09:59 UTC, hdaljord requested changes
Fint at den defaulter til div og ikke h5 👍 

index.d.ts må også oppdateres slik at den stemmer overens med propTypes.

2020-11-20 14:10 UTC, steffenz commented
Jeg driver å gjennomgår denne nå, og skal komme med tilbakemeldinger på typer o.l etterhvert - men så langt ser det veldig bra ut 👍  En av de første tingene som slår meg er imidlertid at det de fleste andre steder bare er brukt ordet "element" og ikke "HTMLElement" på props der man sender inn hvilken tag man skal bruke (eksempelvis på knapper, og kort). Jeg synes likevel "headerHTMLElement" er bedre enn "headerElement" så jeg har egentlig ikke noe godt svar på hva vi bør gjøre. Hva tenker du om det? Er jo kanskje uansett et litt annet case siden vi her snakker om et "barn" av hovedelementet.

2020-11-20 14:34 UTC, ivarni commented
Fra et konsument-perspektiv hvis jeg feks er vant til å bruke `<Grid element="form">` andre steder så er det veldig fint å kunne bruke samme prop-navn her. Men samtidig har jo typescript-filene gitt oss ganske godt fungerende intellisense når vi bruker disse komponentene så jeg hadde nok funnet fram uansett. 

Enn så lenge blir HTML i navnet litt smør på flesk etter min mening, selvom jeg forstår motivasjonen siden den er låst til `string` og derfor ikke kan være en komponent. (I `ffe-buttons-react` er det litt irriterende at jeg ikke kan sende inn react-router's `Link` men akkurat her er det vel helt greit at den bare tar strings).

Jeg har med andre ord heller ikke noe godt svar, men jeg heller mot `element` siden det er brukt andre steder, selvom det vel ikke er helt konsekvent om de tar `string` eller `node` rundt omkring.

2020-11-20 14:35 UTC, ivarni submitted a review, later dismissed

2020-11-20 14:44 UTC, ivarni commented
En generell opprydding og konformering (er det et ord?) av APIene til de forskjellige modulene hadde sikkert vært helt supert. Designsystemet består stort sett av komponenter som er flyttet ganske rett inn hit fra mange forskjellige teams med medfølgende små forskjeller i APIene. Et godt eksempel er at noen komponenter har aliaset `aria-invalid` til `ariaInvalid` mens de fleste (heldigvis) ikke har det. Det er jo en litt større og mer disruptiv operasjon men hvis det er noe man en gang har lyst til å gjøre kan jo sånne diskusjoner som det her bli ganske nyttige.

Og jeg merker at det er slitsomt å skrive på norsk om programmeringsting 😅 

Også: beklager digresjon.

2020-11-23 10:03 UTC, steffenz commented
Mange gode innspill her, @ivarni. Jeg er forresten også enig i at det er litt merkelig å skrive på norsk (men jeg skal ikke ta hele den diskusjonen på nytt :joy:) Ting ser ellers bra ut fra min side, det eneste måtte være typene som blir nevnt (og da er det vel strengt tatt bare ```headerHTMLElement``` som er endra på? Tror normen er at TypeScript ikke skal være strengere enn PropTypes (mulig @hdaljord har innspill her), men da burde det holde å slenge inn ```headerHTMLElement?: string;``` på linje 12 i index.d.ts filen. 

Ellers må du oppdatere en test som feiler på å sjekke at header elementetet er av typen header. Jeg vet ikke om det er noe poeng i å begrense hvilke typer tagger som er tillatt - men det vil i tilfelle krever endringer i propTypes og TypeScript også. Testen det er snakk om ligger i ```ContextMessage.spec.js``` og starter på line 33. Kjør ```npm run test``` (eller kjør denne testen alene) for å se resultatet. Litt usikker på hva som er lureste måten å løse denne på, men kanskje hente ut på klassenavn istedet for elementtype er en begynnelse? Bare si fra om jeg kan bidra med noe her!

2020-11-24 06:58 UTC, hdaljord commented
Ja, @steffenz, jeg tror det er lurt at typescript-typene ikke er strengere enn propTypes. Det blir nok fort frustrerende om ting som er mulig og lov i javascript ikke fungerer om du bruker typescript.

2020-11-26 12:45 UTC, HeleneKassandra commented
Hei takk for tilbakemeldinger!
Da har jeg endret navnet på prop til element,  jeg har også fikset den testen som feilet ved å sjekke på klassenavn istedenfor element. Har også lagt til typings i index.d.ts.

Vi bør nok legge inn en test for å sjekke om den genererer riktig  element basert på input? Er ikke noe dreven i Enzyme / jest, så hvis du har litt tid til å se på det med meg @steffenz  hadde det vært fint :D

2020-11-27 08:57 UTC, hdaljord commented on packages/ffe-context-message-react/src/ContextMessage.js
> +    headerHTMLElement: 'div',
Denne skulle sikkert også vært renamet?

2020-11-27 14:01 UTC, kwltrs commented
> Vi bør nok legge inn en test for å sjekke om den genererer riktig element basert på input?

Jeg la inn en commit på denne branchen som gjør akkurat det. Også fikset jeg en test false positiv test.

2020-11-27 14:02 UTC, kwltrs commented on packages/ffe-context-message-react/src/ContextMessage.spec.js
> -            .find('header');
Denne testen er en false positiv.

2020-12-03 14:10 UTC, HeleneKassandra commented on packages/ffe-context-message-react/src/ContextMessage.spec.js
> -            .find('header');
Hmm.. Testen så litt annerledes ut når jeg gjorde endringene mine nå, så du nærmere på denne, eller skal jeg gjøre det?

2020-12-03 14:10 UTC, HeleneKassandra commented
@kwltrs  Jeg prøvde meg på en fixup, men endte med å få med meg den fixup demoen du viste meg 🤦

2020-12-08 11:18 UTC, kwltrs approved these changes

2020-12-09 06:46 UTC, hdaljord approved these changes

2020-12-11 12:22 UTC, merged

2021-05-16 06:49 UTC, ivarni commented
Det burde nok ha vært markert som en breaking change at man endret prop-navn fra _"header"_ til _"headerText"_, jeg satt nettopp og oppdaterte avhengigheter og husket ikke denne PRen (jeg ser bare i changelog når jeg oppdaterer ting) men ble heldigvis reddet av en cypress-test som oppdaget at alle meldingsboksene våre plutselig mistet overskriften sin :)